#1039 move schema definition into row repository files
openmsupply/remote-server pull request #1060
Opened 2022-04-29 01:42 UTC by roxy-dao

#1039 

Moved all the schemas that can be moved to their relative row repository files. Not sure what to do with the rest of the joinable definitions 🤔

2022-05-01 21:21 UTC, clemens-msupply approved these changes
Great work quite a lot of changes! I haven't looked through all of them in details. @andreievg do you want to have a quick look as well?

2022-05-01 21:33 UTC, clemens-msupply commented
> #1039
> 
> Moved all the schemas that can be moved to their respective row repository files. Not sure what to do with the rest of the joinable definitions thinking

Can't you move them to the respective files as well? or is there a reason you left them there?

2022-05-02 00:26 UTC, andreievg commented on graphql/general/src/queries/invoice_counts.rs
> +use repository::db_diesel::{InvoiceRowStatus, InvoiceRowType};
in the draft PR for the issue, re-export were done in such a way that wouldn't require changes outside of repository crate (was trying to avoid mass changes in this refactor).  Now that the work is done though, happy to keep it, `but` not a fan of importing from db_diesel (should be just from repository, and I think it's already re-exported in `db_diesel/mod.rs` so should work for most of them).

can you please:

* not import from db_diesel (just from repository)
* remove `pub` from db_diesel/mod.rs for modules that are exported with use ..::* (i.e `pub mod invoice_row` -> `mod invoice_row`)

2022-05-02 00:38 UTC, andreievg requested changes
Great, thanks for all of the changes.

Please do a check with postgres features, `cargo check --features postgres`, some warnings and compilation.

Also i've made a comment about imports from `db_diesel`.

Lastly:
* `pricing` is used in `invoice_line.rs`, I think it should move there (ideally we would create it's own repository for stats vs keeping it in InvoiceLineRepository, but for now it's ok to just relocate the schema definition to `invoice_line.rs`
* `sync_out` is not used, can be deleted

I think at this stage we can remove repository/src/schema and relocate diesel_schema to db_diesel/mod.rs (I think all of the joinable and allow_tables_to_appear_in_same_query to be there)

DatabaseRow is not used btw, can be deleted

2022-05-02 22:33 UTC, roxy-dao commented
> I think at this stage we can remove repository/src/schema and relocate diesel_schema to db_diesel/mod.rs (I think all of the joinable and allow_tables_to_appear_in_same_query to be there)

the joinables and allow_tables_to_appear_in_same_query will have name conflicts if relocated to db_diesel/mod.rs as the tables have the same name as the modules. I can move the whole diesel_schema to the /db_diesel which would avoid those name conflicts.

2022-05-03 00:59 UTC, clemens-msupply commented
> > I think at this stage we can remove repository/src/schema and relocate diesel_schema to db_diesel/mod.rs (I think all of the joinable and allow_tables_to_appear_in_same_query to be there)
> 
> the joinables and allow_tables_to_appear_in_same_query will have name conflicts if relocated to db_diesel/mod.rs as the tables have the same name as the modules. I can move the whole diesel_schema to the /db_diesel which would avoid those name conflicts.

Would it help to move content to db_diesel to schema?, i.e. only have one directory? The initial reason we had a db_diesel dir was that we had an alternative sqlx implementation of the repos. But now we are pretty much fixed on diesel and we don't really need a separate dir anymore...

2022-05-03 01:05 UTC, andreievg commented
> Would it help to move content to db_diesel to schema?, i.e. only have one directory? The initial reason we had a db_diesel dir was that we had an alternative sqlx implementation of the repos. But now we are pretty much fixed on diesel and we don't really need a separate dir anymore...

Hmm, i like the idea of renaming db_diesel (although schema is not quite descriptive enough?). I think we can make an issue for it to discuss repository crate structure, would be good to get this PR merged with minimum changes.

2022-05-03 01:35 UTC, clemens-msupply commented
Just noticed that the file [omsupply-database](https://github.com/openmsupply/remote-server/pull/1060/files#diff-0d193775762ef517ba9b192165a9dc43657aaad3eb10ab536d6fe85e40ab95b4) got committed. Could you please do an interactive rebase to remove it from the git history (its 200kb). I can help you with it if you haven't done it before...

2022-05-03 01:50 UTC, clemens-msupply commented
just had a look at joinables again. I would move them to the matching table! macro because they describe which column are foreign keys, e.g.:

```rust
table! {
    invoice_line (id) {
        id -> Text,
        invoice_id -> Text,
        item_id -> Text,
        item_name -> Text,
        item_code -> Text,
        stock_line_id -> Nullable<Text>,
        location_id -> Nullable<Text>,
        batch -> Nullable<Text>,
        expiry_date -> Nullable<Date>,
        pack_size -> Integer,
        cost_price_per_pack -> Double,
        sell_price_per_pack -> Double,
        total_before_tax -> Double,
        total_after_tax -> Double,
        tax -> Nullable<Double>,
        #[sql_name = "type"] type_ -> crate::db_diesel::invoice_line_row::InvoiceLineRowTypeMapping,
        number_of_packs -> Integer,
        note -> Nullable<Text>,
    }
}

joinable!(invoice_line -> item (item_id));
joinable!(invoice_line -> stock_line (stock_line_id));
joinable!(invoice_line -> invoice (invoice_id));
joinable!(invoice_line -> location (location_id));
```

2022-05-04 01:36 UTC, andreievg approved these changes

2022-05-04 01:36 UTC, andreievg commented
thank you and great work

2022-05-04 03:53 UTC, merged