#211 improve mechanism for initialising database (WIP)
openmsupply/remote-server pull request #232
Opened 2021-07-27 01:23 UTC by wlthomson

This is a WIP (mostly just missing some mock data), so not ready for merging yet. PRing to give visibility as I am away from 28/07-1/08.

2021-08-17 00:40 UTC, andreievg requested changes
Looks good, just a minor change request.

(haven't reviewed any mock stuff thought, would have been better in seperate PR imo). There is another way to do testing, which is fast and uses db, I'll make an issue with explanation. Anyways if we choose to go with mocks I'll give it a more thorough review in the future.

Also would be great if main method jumped up an abstraction level (still have logic in main.rs, but with helper methods), we can do this in seperate PR in the future, once we know what are all the bits that need to be in main

i.e. (something along these lines)
```
setupLogging();

let settings = getSetting();

let repository = getDBRepository(&settings)

startScheduler(&repository)

let syncConsumer = initiliseSync(&repository)

let startWebServer(&repository, &settings)
```

2021-08-18 01:00 UTC, andreievg commented on src/main.rs
> +pub fn get_repositories() -> RepositoryMap {
@wlthomson

2021-08-18 04:26 UTC, wlthomson commented
> 
> 
> Looks good, just a minor change request.
> 
> (haven't reviewed any mock stuff thought, would have been better in seperate PR imo). There is another way to do testing, which is fast and uses db, I'll make an issue with explanation. Anyways if we choose to go with mocks I'll give it a more thorough review in the future.
> 
> Also would be great if main method jumped up an abstraction level (still have logic in main.rs, but with helper methods), we can do this in seperate PR in the future, once we know what are all the bits that need to be in main
> 
> i.e. (something along these lines)
> 
> ```
> setupLogging();
> 
> let settings = getSetting();
> 
> let repository = getDBRepository(&settings)
> 
> startScheduler(&repository)
> 
> let syncConsumer = initiliseSync(&repository)
> 
> let startWebServer(&repository, &settings)
> ```

Yup, agreed 100%. Idea is that `main.rs` should just be an entry-point which uses functionality exposed by the crate. So I agree completely with lifting business logic out into functions etc.

2021-08-18 04:27 UTC, wlthomson commented on src/main.rs
> +pub fn get_repositories() -> RepositoryMap {
Agreed. I think this is an instance of your main comment about needing more abstraction in `main.rs`. Maybe best to make an issue so this stuff can get merged in the meantime?

2021-08-18 04:32 UTC, andreievg approved these changes

2021-08-18 04:44 UTC, merged