Add SyncSettings to configuration
openmsupply/remote-server pull request #239
Opened 2021-08-15 22:40 UTC by wlthomson

Closes #215.

Lots of stuff here, but should build a decent foundation for other issues in #236 (although goes a bit out-of-scope as also includes some implementation logic for pulling remote records).

2021-08-17 03:28 UTC, andreievg requested changes
Look very good! A few change requests thought.

Haven't reviewed the test, looks like they are trying to mock real server (which is ok for now but, actual integration tests need to be done against real services).

2021-08-17 03:28 UTC, andreievg commented on src/util/sync/connection.rs
> +        let credentials = SyncCredentials::new(username, password);
don't need to clone any of the strings, just pass as ref

2021-08-17 03:28 UTC, andreievg commented on src/util/sync/connection.rs
> +        headers.insert(CONTENT_LENGTH, "0".parse().unwrap());
surely reqwest handles this automatically ?

2021-08-17 03:28 UTC, andreievg commented on src/util/sync/connection.rs
> +            .headers(headers);
i see where you are heading with sync `SyncCredentials` and `SyncServer`, i think a little bit more abstraction would be good (combine the two and the client, so that methods in SyncConnection can all use that abastraction)

2021-08-17 03:28 UTC, andreievg commented on src/util/sync/connection.rs
> +        const BATCH_SIZE: u32 = 500;
this is also a setting

2021-08-17 03:28 UTC, andreievg commented on src/util/sync/connection.rs
> +            .headers(headers);
Also it can include some basic error handling

2021-08-17 03:28 UTC, andreievg commented on src/util/sync/mod.rs
> +            if let Some(data) = sync_batch.data {
FYI, there are two different ways to sync records, central log and sync queue.

With central log we increment counter.

With sync queue we acknowledge, for acknowledge we would store acknowledgement if it fails to sync (at which stage we stop sync and on start sync we try to send acknowledgement first).

Don't need to worry about that in this PR but something to be aware of

2021-08-20 01:23 UTC, wlthomson commented on src/util/sync/connection.rs
> +        let credentials = SyncCredentials::new(username, password);
Required a bit of refactoring (and still need to do some cloning, as moving `username` into a struct), but maybe this is more what you were thinking: 1c1991d.

2021-08-20 01:29 UTC, wlthomson commented on src/util/sync/connection.rs
> +        headers.insert(CONTENT_LENGTH, "0".parse().unwrap());
Doesn't seem so. If you remove this, server will reject the request! My guess is that `reqwest` doesn't generate `content-length` headers for `POST` requests without bodies.

2021-08-20 01:30 UTC, wlthomson commented on src/util/sync/connection.rs
> +            .headers(headers);
Yeah I agree with all this... I stopped because the PR was already getting pretty big. I want to get this merged so I can use it as a base for some gql investigation, do you have a problem with this abstraction being done in another PR?

2021-08-20 01:32 UTC, wlthomson commented on src/util/sync/connection.rs
> +        const BATCH_SIZE: u32 = 500;
I wasn't sure if it would cause some angry reactions if I put this into the `.yml` configs! As above, ok for this to be done in a separate PR (I'm also aware my PRs are quite big lately, so I'm trying to break tasks down into easier to review chunks)?

2021-08-20 01:33 UTC, wlthomson commented on src/util/sync/mod.rs
> +            if let Some(data) = sync_batch.data {
Yup, I just focused on sync queue here as the central log required a bit more fiddling with cursors etc!

2021-08-23 07:55 UTC, merged

2021-08-23 07:55 UTC, wlthomson commented
Merging this so that branches don't fall too far behind now that @clemens-msupply is starting to work on this.