#257 Add a initial version of a Diesel repository
openmsupply/remote-server pull request #266
Opened 2021-08-26 03:06 UTC by clemens-msupply

~~Not really ready for merging yet since completely untested (Plan to work on some automatic testing first). Just want to share my progress / get some feedback.~~

My initial feeling about diesel:
- a bit cumbersome to use, lots of files to edit, lots of magic
- really doesn't like code to be shared between DB's but ok when using a feature flag. I tried to make the diesel repo generic to the connection pool but it wasn't possible; due to my bad Rust skills? I failed far down in the associated type def of the diesel Connection trait: low level data type [u8] is incompatible to sqlites internal data type...
- support for enums in sqlite and pg seems possible :)

2021-08-29 04:43 UTC, wlthomson commented on src/database/repository/diesel/item_line.rs
> +use super::DBBackendConnection;
As above.

2021-08-29 04:43 UTC, wlthomson commented on src/database/repository/diesel/item.rs
> +use super::DBBackendConnection;
Minor formatting nits. Some general rust conventions, some more arbitrary and specific to this project - hopefully nothing too controversial!

1. Squash imports which have a shared root crate. 
2. Avoid importing same crate from different namespaces (e.g. `r2d2` vs. `diesel::r2s2`).
3. Local imports grouped at the top of the file, external crates imported afterwards (separated by a newline).

E.g.

```suggestion
use super::DBBackendConnection;
use crate::database::{
    repository::{repository::get_connection, RepositoryError},
    schema::ItemRow,
};

use diesel::{
    prelude::*,
    r2d2::{ConnectionManager, Pool},
};
```

2021-08-29 04:43 UTC, wlthomson commented on src/database/repository/diesel/mod.rs
> +use crate::{server::data::RepositoryMap, util::settings::Settings};
As above.

2021-08-29 04:43 UTC, wlthomson commented on src/database/repository/diesel/mod.rs
> +}
Very nice!

2021-08-29 04:43 UTC, wlthomson commented on src/database/repository/diesel/mod.rs
> +            diesel::result::Error::DatabaseError(err, _) => {
Can probably tidy this up by importing something like:

```
use diesel::result::Error as DieselError
...
    let msg = match err {
        DieselError::InvalidCString(_) => "DIESEL_INVALID_C_STRING".to_string(),
        ...
...
```

2021-08-29 06:16 UTC, wlthomson requested changes
Phew. Quite a lot to cover here... Need to attend to some errands and don't want to lose pending comments!

2021-08-29 06:16 UTC, wlthomson commented on tests/repository/basic.rs
> +        user_account_test(repos.get::<UserAccountRepository>().unwrap()).await;
Firstly, awesome that you're adding tests! 

Secondly, testing with databases is a hard problem, and I don't have a good solution yet.

With those disclaimers in mind:

I think you've come up against the first big problem that arises with unit/integration testing involving databases.

Researching properties of good tests, one of the main ones that comes up a lot is "isolated" or "decoupled". I.e., no test pass or failure should depend on another test. There's lots of good articles on this - just a few I found:

- https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-best-practices 

I think a reasonable response to this article would be question whether these rules should apply to integration tests. I've included these other articles as I think they are useful in thinking about this question (TLDR; "narrow" integration tests should be preferred over "broad", integration tests should be isolated).

- https://www.pluralsight.com/tech-blog/what-kind-of-test/
- https://martinfowler.com/bliki/IntegrationTest.html

Interested in your thoughts on this!

2021-08-29 21:26 UTC, clemens-msupply commented on src/database/repository/diesel/item.rs
> +use super::DBBackendConnection;
Any automated tooling for it?

2021-08-29 21:48 UTC, chris-morgan commented on src/database/repository/diesel/mod.rs
> +        msg: "Failed to open Connection".to_string(),
Actually, `"…".to_string()`, `"…".to_owned()`, `String::from("…")` and `"…".into()` all perform the same [since Rust 1.9](https://stackoverflow.com/a/31333653) (and since we’re talking about literals, `format!("…")` should be the same too, though for somewhat different reasons). This is achieved with an unstable feature called [specialisation](https://rust-lang.github.io/rfcs/1210-impl-specialization.html); `ToString` is implemented by [all types that implement `std::fmt::Display`](https://doc.rust-lang.org/1.54.0/src/alloc/string.rs.html#2372-2386), but that’s written as a *default* implementation, so you can also override the behaviour for more specific types to do the same thing more efficiently (`std::fmt` isn’t terribly heavy but isn’t the lightest thing in the world either), and [`str` does this](https://doc.rust-lang.org/1.54.0/src/alloc/string.rs.html#2442-2447).

Concerning which one you should use, then, opinions differ widely. I myself would probably most commonly use `.to_string()` or `.into()` (very broadly useful, at least so long as the types can be inferred, but tends to require more context to understand). But frankly, I’d consider the use of `String` like this *at all* to be at least a minor code smell. This is the sort of place where an enum is desirable; something like the `thiserror` makes defining such error types very smooth. One other option, if you really wanted strings that can be dynamic but normally don’t need to be, is `Cow<'static, str>` (which is basically “either `&'static str` or `String`”), and use `"".into()`; that way you can avoid an allocation in the typical case where you’re not interpolating anything into the string. (But don’t become *fanatical* about avoiding allocations just because it’s possible to, if it makes life any harder.)

2021-08-29 21:49 UTC, clemens-msupply commented on src/database/schema/diesel_schema.rs
> +    type_of -> crate::database::schema::item::ItemRowTypeMapping,
Doesn't seem to like it. Must be some macro issue because ItemRowTypeMapping is auto generated.

2021-08-29 21:51 UTC, chris-morgan commented on src/database/repository/diesel/requisition.rs
> +        return result.map_err(|err| RepositoryError::from(err));
I’d spell this `Ok(result?)`. `?` does a `From` conversion of the error type.

2021-08-29 21:56 UTC, chris-morgan commented on src/database/repository/diesel/requisition.rs
> +        return result.map_err(|err| RepositoryError::from(err));
Well actually, I’d be inclined to reduce the number of expressions, merging it with at least the line above, and quite possibly reducing the entire method body to one expression:

```rust
        Ok(requisition
            .filter(id.eq(requisition_id))
            .first(&get_connection(&self.pool)?)?)
```

(Mind you, this is not quite equivalent, because it evaluates `id.eq(requisition_id)` before the connection early return, though in practice I expect that stuff to be pure and near enough to a noop that it won’t make any difference.)

2021-08-29 21:57 UTC, clemens-msupply commented on src/database/repository/diesel/mod.rs
> +        msg: "Failed to open Connection".to_string(),
Thanks for the info. Yes agree we should us an error enum for our RepositoryError. For example, at the moment we lose "soft" errors like "row already exists" when inserting something into the DB. However, this might be something we want to handle differently...

2021-08-29 21:59 UTC, chris-morgan commented on src/main.rs
> +
Actually, from the Rust 2018 edition onwards, writing `extern crate` or `#[macro_use]` at all is bad style (except for about one case if I recall correctly, `#[cfg(test)] extern crate std;` in a no-std crate); import the macros in each module as you use them instead.

2021-08-29 23:57 UTC, clemens-msupply commented on src/main.rs
> +
What would be the alternative?

I just removed it and the code still compiles. If I remember correctly I had to include it earlier when using Diesel's migration macro. However, not using it at the moment...

Think it was related to: https://github.com/diesel-rs/diesel/issues/1764

2021-08-30 00:05 UTC, clemens-msupply commented on src/database/repository/diesel/requisition.rs
> +        return result.map_err(|err| RepositoryError::from(err));
Thanks was wondering how to use ::from automatically :)

I find it's a bit of a tradeoff: concise vs readable/debuggable. E.g having an extra variable helps to see the current type of the query in the IDE while developing. Later on its also easier to set a breakpoint and see what is returned...

This example, is very simple but I find one or more extra vars very useful when there are constructs like map().map().reduce().flatMap() where the type changes multiple time...

happy to use it either way though

2021-08-30 00:12 UTC, chris-morgan commented on src/main.rs
> +
`#[macro_use]` makes it so that all the crate’s macros marked `#[macro_export]` are brought into scope at all levels, so you can write `aleph!()` without needing to write `use diesel::aleph;` first. The trouble is with crates that still write things the old way and generate `beth!()` instead of `diesel::beth!()`. From 2018, `#[macro_use]` is never *essential*, but if you call a macro that calls other macros in the old style, you’ll need to import them too, e.g. if `diesel::aleph!()` generates `beth!()`, you’ll need to write a `use diesel::beth;` in any module you invoke aleph, even though “beth” doesn’t occur in the code you type.

2021-08-30 01:52 UTC, chris-morgan commented on src/database/repository/diesel/requisition.rs
> +        return result.map_err(|err| RepositoryError::from(err));
Most IDEs combined with rust-analyzer will be pretty good about type discovery regardless of the way you write it; if you have inlay hints available and enabled, you should even get the type written at the end of each line when you’ve got multi-line chaining going on, and apart from that you can also hover over things to get type tooltips.

Another couple of ways of writing `.map_err(|err| RepositoryError::from(err))` are `.map_err(RepositoryError::from)` and `.map_err(From::from)`. But the `?` operator with its automatic conversion is really nice, it just becomes the non-obvious `result` → `Ok(result?)`. Splitting that out into another line can certainly make it easier to follow when you’re not deeply familiar with the patterns involved, and even often if you are:

```rust
        let connection = get_connection(&self.pool)?;
        let row = requisition
            .filter(id.eq(requisition_id))
            .first(&connection)?;
        Ok(row)
````

2021-08-30 07:21 UTC, clemens-msupply commented on tests/repository/basic.rs
> +        user_account_test(repos.get::<UserAccountRepository>().unwrap()).await;
Yes the test got bigger over time... I first only had tests that tested one repo at a time in the same DB. But that was before I realized that there are foreign key constraints I tests write into different table. So yes I could split the big test into one test for each repository. For each test I would init a fresh DB, populate the required data and do the test. This means quite a bit more boilerplate. Worth the effort? happy to refactor though! 

Regarding best testing practice I really don't want to start a big discussion. Its like C++ vs C, functional vs OOP, for every argument you can find a counter argument ;-) My take on it is that I try to follow "best practice" and be aware of it but if I see a good reason to do it differently I don't feel bad to not follow it. For example, if you have to write lots of mocks just to keep unit tests isolated/decoupled then its often just easier to use other units to get your test into the correct state. This can even lead to more robust tests, e.g. who tests that your mocks are correct? Or why have decoupled unit tests if you units are coupled? I am quite pragmatic about it... But yes test should be narrow and only touch one aspect if possible and I try to follow this even for integration tests.

Rust tests are multi-threaded on default, right? so technical you can't have tests that depend on other tests (wrong see my test function) ;-)

2021-08-30 07:23 UTC, clemens-msupply commented on src/database/repository/diesel/requisition.rs
> +        return result.map_err(|err| RepositoryError::from(err));
Thanks, I do it like this now.

2021-08-30 09:45 UTC, wlthomson commented on tests/repository/basic.rs
> +        user_account_test(repos.get::<UserAccountRepository>().unwrap()).await;
I agree re. not starting a big discussion! As I said I don't have a perfect solution, I'm just flagging this up as something we might want to have a look into when it is of appropriate priority (I think this PR is big enough already, so I think we can rule out refactoring here!).

2021-08-30 09:48 UTC, wlthomson commented on src/database/repository/diesel/item.rs
> +use super::DBBackendConnection;
Not at the moment. Could update `rustfmt` to help out with some of it, if you agree with it?

2021-08-30 09:52 UTC, wlthomson approved these changes
LGTM!

2021-08-31 08:20 UTC, merged