#263 Add item properties tables
openmsupply/remote-server pull request #269
Opened 2021-08-26 05:02 UTC by wlthomson

Closes #263.

Have purposely avoided adding repository methods for `item_property_join` (see #268).

2021-08-29 21:16 UTC, clemens-msupply approved these changes

2021-08-29 21:16 UTC, clemens-msupply commented on src/database/schema/item_property_join.rs
> +    pub value: JsonValue,
For both ItemPropertyRow and ItemPropertyJoinRow it would be good to have some comments for the structs members. For example, what it the item property key? What is the relationship between ItemPropertyRow and ItemPropertyJoinRow.

2021-08-29 21:16 UTC, clemens-msupply commented on src/database/schema/item_property_join.rs
> +    pub value: JsonValue,
How is the JsonValue used later on? with sqlite in mind would it be easier to store it as a string and then parse it when needed?

2021-08-31 03:08 UTC, andreievg requested changes

2021-08-31 03:08 UTC, andreievg commented on migrations/20210825070620_create_item_property_join.sql
> +    value jsonb NOT NULL
the value is on the property

2021-08-31 04:08 UTC, andreievg commented on migrations/20210825070620_create_item_property_join.sql
> +    value jsonb NOT NULL
I've dismissed the review, because I am actually not sure what the full intention of property is. Should be ok on property join for now

2021-08-31 19:36 UTC, clemens-msupply commented on migrations/20210825070620_create_item_property_join.sql
> +    value jsonb NOT NULL
had problems with that as well though, `value` would make more sense to be in `item_property`?

2021-09-02 07:58 UTC, wlthomson commented on migrations/20210825070620_create_item_property_join.sql
> +-- Create item_property_join table
Yeah, that's definitely true (also duplicated in the filename!). It's more just trying to establish a convention that all migrations should have a top-level comment summarising what the migration does. Agree that for the initial migrations this is completely redundant, but it'll probably be a nice convention to stick with (also all migrations have these comments already, so there's not much point removing this one unless we remove them all)!

2021-09-08 12:21 UTC, andreievg commented
I would put this on hold until
A - We agree on schema
B - We set a milestone for it

2021-09-11 08:24 UTC, wlthomson commented
Converted to WIP as is on hold.

2022-02-17 03:26 UTC, andreievg commented
doing PR clean up, so closing, will know it's here for reference

2022-02-17 03:26 UTC, closed without merging