281 simple translation 2
openmsupply/remote-server pull request #314
Opened 2021-09-08 08:46 UTC by clemens-msupply

This aims to implement the translaions as we discusses last time.

There are two things that I am not entirely happy with but couldn't fix to this point (because of Rust type and async issues).
1) After another discussion with Will we realized that Andrei and me probably planted to use something more closer to a DAO pattern and that DAO and repository pattern are complimentary (e.g. https://www.baeldung.com/java-dao-vs-repository). For this reason I did some experimenting using a DAO layer between ORM and Repository where the Repository layer is mostly independent from Diesel and only uses the DAO layer. However, I run into some further async issues and gave up on it. However, I think it might be an options to move the auxilary methods like `pub fn insert_one_tx(connection: &DBConnection, name_row: &NameRow)` out of the Repositories into something like `NameQueries` to keep the Repositories more tidy.

2) Upsert for sqlite is only supported in the upcoming Diesel 2.0 version. I wasn't manages to implement the upsert in a generic way, i.e. upsert for sqlite must be implemented multiple times and doing the raw queries is a bit error prone (easy to forget to add new table columns).

Closes #281

2021-09-08 09:55 UTC, wlthomson commented
@clemens-msupply thanks again for that article, it articulates what I was trying to say about repos != DAOs better than I was able to. The key summary I think I was going for was:

> In other words, a repository also deals with data and hides queries similar to DAO. However, it sits at a higher level, closer to the business logic of an app.

**Disclaimer: what comes below is just to help clarify why I suggested the approach I did, if others still disagree, I'm happy to move forward with a more hybrid "DAO-repo" interpretation where the repo is kept segregated from any domain layer business logic.**

This is the justification behind my preference for the sync repo methods to take domain model structs rather than already mapped ones. I think it would be really nice if the sync actors only have to exist at the domain model level and just worry about sending and receiveing sync records as they are structured in the sync API (ahd leave all the mapping between the domain objects and database objects to the repos). Hopefully it also helps explain what I meant by saying that ideally transactions would be kept at the repo level? I think one way to conceptualise transactions is as part of the mapping between the domain model and the database model, in that they are mapping a single atomic domain level operation, e.g. integration a list of records, into multiple database level operations on multiple database entities.

Anyways, will get on with a proper review now. Just wanted to acknowledge my appreciation for the searching for that article and having a go at incorporating the approach. I feel a lot better moving forward now that we've considered it even if we end up taking a different approach.

2021-09-08 11:47 UTC, andreievg requested changes
Thanks Clemens!

Very easy to read and follow.
I would typically recommend PR's under 200 lines, but I've been guilty of submitting large one. And code is super easy to follow so I guess it's ok.

A few changes and questions

can you please do cargo check --features sqlite (and postgres) and get rid of warning.

> Upsert for sqlite is only supported in the upcoming Diesel 2.0 version. I wasn't manages to implement the upsert in a generic way, i.e. upsert for sqlite must be implemented multiple times and doing the raw queries is a bit error prone (easy to forget to add new table columns).

I've left a note about this, i think we should keep static as much as possible (since keeping static was one of the main reasons for diesel)

well written but break it down

2021-09-08 11:47 UTC, andreievg commented on src/database/repository/diesel/item.rs
> +        let q = diesel::sql_query(query)
I kind of thought the point of diesel was to maximise the static typing.. 
At this stage I would rather query for existence of ID and do insert or update (generic code for both), vs using raw sql.

2021-09-08 11:47 UTC, andreievg commented on src/database/repository/diesel/item.rs
> +        ItemRepository::insert_one_tx(&connection, item_row)?;
insert_one_tx has the same return type and insert_one

2021-09-08 11:47 UTC, andreievg commented on src/database/repository/diesel/mod.rs
> +pub type DBConnection = PooledConnection<ConnectionManager<DBBackendConnection>>;
nice

2021-09-08 11:47 UTC, andreievg commented on src/database/repository/diesel/item.rs
> +    pub fn upsert_one_tx(
i feel like `_tx` implies transaction too much. Wonder what the practice in in rust of utility methods, from my understanding it's underscore, i.e. `_upsert_one` (at least form the code i've been reading)

2021-09-08 11:47 UTC, andreievg commented on src/database/repository/diesel/name.rs
> +    pub fn find_one_by_id_tx(
do we really need to be extracting all methods to associated methods like this ? Would be good to touch just the bits that are in scope for an issue

2021-09-08 11:47 UTC, andreievg commented on src/database/repository/diesel/sync.rs
> +#[derive(Clone)]
ohh, just realised, we actually clone every repository with `registry.get::`. I guess derive would call `pool.clone()`. I wonder if we need to optimise that at some stage (just noting)

2021-09-08 11:47 UTC, andreievg commented on migrations/postgres/00000105_create_item_table/up.sql
> +CREATE TYPE item_type AS ENUM ('general', 'service', 'cross_reference', 'none_stock');
I think we should remove it form schema, so we know that tables we touch are 'clean' fully translated up to the current spec

2021-09-08 11:47 UTC, andreievg commented on src/util/sync/translation/item.rs
> +        _ => panic!("unknown type"),
relax : ), even though this will be refactored, please no panics

2021-09-08 11:47 UTC, andreievg commented on src/util/sync/translation/item.rs
> +fn match_item_type(type_of: String) -> ItemRowType {
although i think this needs to be removed, but fyi, you can give a 'default' value if enums is not matched:
```rust
#[derive(Deserialize, Serialize, Debug)]
enum Check {
    A,
    B,
    #[serde(other)]
    Unknown,
}
```
if value being deserialised is neither A or B, Unknown will be used

2021-09-08 11:47 UTC, andreievg commented on src/util/sync/translation/item.rs
> +    #[tokio::test]
is tokio the runtime used by actix_web ? wonder if we should be testing in same runtime or if it doesn't matter

2021-09-08 11:47 UTC, andreievg commented on src/util/sync/translation/item.rs
> +    async fn test_item_translation() {
I feel like we should be testing methods in scope, what do you think ? (otherwise it's a small integration test, and they live in `tests` folders apperantly)

2021-09-08 11:47 UTC, andreievg commented on src/database/repository/diesel/sync.rs
> +    pub async fn integrate_records(
any reason to have this async ?

2021-09-08 11:47 UTC, andreievg commented on src/util/sync/translation/mod.rs
> +    if let Some(row) = LegacyNameTable::try_translate(sync_record)? {
What do you think should try_translate return `Option<IntegrationRecord>` ?
Also (and we cross that road when we get there), we might need to return a Vec of IntegrationRecord (for complex translations, but that could be a seperate method)

2021-09-08 11:52 UTC, andreievg commented
> After another discussion with Will we realized that Andrei and me probably planted to use something more closer to a DAO pattern and that DAO and repository pattern are complimentary (e.g. https://www.baeldung.com/java-dao-vs-repository). For this reason I did some experimenting using a DAO layer between ORM and Repository where the Repository layer is mostly independent from Diesel and only uses the DAO layer

I am glad you didn't, because I would have disagreed, two layers of abstraction ORM, and DOA/Repo type is plenty for what we are trying to build.

Also can you please include me in these sorts of discussions. 

@wlthomson I didn't read your post, since we already made a decision. Didn't want to be distracted (wanted to actually focus on getting some work done)

2021-09-08 20:10 UTC, clemens-msupply commented on migrations/postgres/00000105_create_item_table/up.sql
> +CREATE TYPE item_type AS ENUM ('general', 'service', 'cross_reference', 'none_stock');
This was more to make the test work with "real" data. Agree, having the enum makes the schema to restricted. For example, if a newer server version has a new enum member the old server can't sync the new data anymore even though it doesn't need the new enum.

2021-09-08 20:26 UTC, clemens-msupply commented on src/database/repository/diesel/item.rs
> +        let q = diesel::sql_query(query)
Yes good point I was too focused on the upsert syntax. Will do it with INSERT OR REPLACE till diesel supports upsert.

2021-09-09 00:36 UTC, andreievg commented on migrations/postgres/00000105_create_item_table/up.sql
> +CREATE TYPE item_type AS ENUM ('general', 'service', 'cross_reference', 'none_stock');
> For example, if a newer server version has a new enum member the old server can't sync the new data anymore even though it doesn't need the new enum.

I think it's fine with enums, see: https://github.com/openmsupply/remote-server/pull/314#discussion_r704332225

2021-09-09 00:39 UTC, andreievg commented on migrations/postgres/00000105_create_item_table/up.sql
> +CREATE TYPE item_type AS ENUM ('general', 'service', 'cross_reference', 'none_stock');
My point is that the schema that we have is just for prototype reasons, we should be using schema in translated document from now on (to be certain that only agreed on schema is in, and so we don't need to reconsolidate it)

2021-09-09 01:29 UTC, clemens-msupply commented on src/database/repository/diesel/item.rs
> +    pub fn upsert_one_tx(
No idea about utility methods, up to you...

Think tx is quite fitting though because that is exactly what the method is for.

2021-09-09 01:34 UTC, andreievg commented on src/database/repository/diesel/item.rs
> +    pub fn upsert_one_tx(
good point, not fussy, i just saw it used in async method without transaction.
backing down on that request. if we end up using it more frequently we can change

2021-09-09 01:45 UTC, clemens-msupply commented on src/database/repository/diesel/sync.rs
> +    pub async fn integrate_records(
It's only async because other Repositories are having an async interface which is to keep the rest of the system independent from the DB backend / ORM...

2021-09-09 01:52 UTC, clemens-msupply commented on src/util/sync/translation/item.rs
> +    #[tokio::test]
I assumed so but I couldn't really confirm it and I am probably wrong. I will use #[actix_rt::test] instead.

2021-09-09 02:03 UTC, clemens-msupply commented on src/util/sync/translation/mod.rs
> +    if let Some(row) = LegacyNameTable::try_translate(sync_record)? {
The IntegrationRecord was indented to describe the whole job that needs to be done by the SyncRepository (only upserts are currently supported).

I used `try_translate` more like a convention rather than an interface. A complex translation could return a tuple which is then filled into the IntegrationRecord depending on the translation... However, open for changes and probably best to decide when we have an actual complex translation.

2021-09-09 02:39 UTC, clemens-msupply commented on src/util/sync/translation/item.rs
> +    async fn test_item_translation() {
It tricky, depends on how you define unit tests. Here I am testing the unit of "legacy record integration" which has two parts the data translations and the SyncRepository. 

Personally find it easier to have the test close to the main logic but I am fine to move it to integration tests.

For me an integration test would be more like an API call to the running server, but there are multiple schools about it...

2021-09-09 02:41 UTC, clemens-msupply commented on src/util/sync/translation/item.rs
> +    async fn test_item_translation() {
btw. I plan to move the existing repository tests into smaller unit tests, think that would fit better...

2021-09-09 02:51 UTC, clemens-msupply commented
> can you please do cargo check --features sqlite (and postgres) and get rid of warning.

these warning should get fixed once the translation is actually used... Find to ignore these warnings till then?

> Also can you please include me in these sorts of discussions.

sorry about that, it was just a follow up on a chat we had earlier...

2021-09-09 02:52 UTC, andreievg commented on src/util/sync/translation/item.rs
> +    async fn test_item_translation() {
> Personally find it easier to have the test close to the main logic

Wouldn't that mean you would test `try_translate` here (without import_sync_record), and `import_sync_records` in `translation/mod.rs` ? 

Btw that's what i meant by testing methods in scope

2021-09-09 02:59 UTC, clemens-msupply commented on src/util/sync/translation/item.rs
> +    async fn test_item_translation() {
You would basically have the same test case twice, wouldn't you? for this reason I find it easier to do it in one pass...

2021-09-09 02:59 UTC, andreievg commented
Thanks for comments so far, i've unresolved some comments that were marked as resolved (will resolve them with changes), btw I found this process the easier for reviewer:
* Reviewer resolves comments they've made
* Code changes hash is pasted in comment blocks it addresses

2021-09-09 03:03 UTC, andreievg commented
> these warning should get fixed once the translation is actually used... Fine to ignore these warnings till then?

ohh true, some provisionary things will be used upstream

> sorry about that, it was just a follow up on a chat we had earlier...

no problems, sorry i feel like my comment didn't sound like i intended. (it was a soft request of being included in the loop)

2021-09-09 03:16 UTC, andreievg commented on src/util/sync/translation/item.rs
> +    async fn test_item_translation() {
It would point to failing area better, ok to just have one case, but it shouldn't be here (if it's test like this it should probably be in `import_sync_record`. 

I was suggesting:

try_translates checks for deserialisation in this case, assert comparison with result object (don't do any db inserts)

import_sync_record checks that it can integrate multiple records, assert db query result at the end.  (and yes it would double up here, but you would have a much better idea of the origin of the issue ? and when you deving, making further translation for item, you can just run the deserialisation test by it's own, you would have seen the 'play' button rust analyser put on each test )

2021-09-09 04:32 UTC, wlthomson requested changes
Mostly LGTM!

Have realised that a lot of the buffer work I've done will have to be changed to accomodate this. Would be good to get some agreement on how we think that will integrate!

2021-09-09 04:32 UTC, wlthomson commented on src/util/sync/translation/item.rs
> +}
I understand why this is all here, but we could just go yagni and add the fields when they are needed? We will have this commit in the history, so can always grab these fields from there if the idea is to save time later!

2021-09-09 04:32 UTC, wlthomson commented on src/database/repository/diesel/sync.rs
> +                        NameRepository::upsert_one_tx(&connection, record)?
Is the idea that this would be replaced with buffer inserts? Or would integration records be taken from the buffer after a full sync had occurred?

2021-09-09 04:35 UTC, wlthomson commented on src/database/repository/diesel/sync.rs
> +    pub async fn integrate_records(
Not sure if this was accidentally resolved but I think this is an important question to get an answer to as I'm quite confused by the pattern we are using and how we expect buffering to work with it.

2021-09-09 04:37 UTC, clemens-msupply commented on src/util/sync/translation/item.rs
> +    async fn test_item_translation() {
especially if you know recent commits it should be easy to find the origin (if the test ever breaks). 

I thought about it (probably too long now ;-) ) but I only see theoretical benefits for splitting the tests. I see some disadvantages though:
- more annoying to write (quite a strong point for me, e.g. why spend time on a "boring" repetitive task while it can be avoided)
- as said, to get equivalent sorrow tests you need to feed the same data to both, the translation and RepositorySync, this will be quite error prone

Your call...

2021-09-09 04:46 UTC, clemens-msupply commented on src/util/sync/translation/item.rs
> +impl LegacyItemRow {
Agree, I only did it because there was an enum in there before for which reason I couldn't use From. I already use from for Name.

See discussion above for test location...

2021-09-09 04:50 UTC, clemens-msupply commented on src/database/repository/diesel/sync.rs
> +                        NameRepository::upsert_one_tx(&connection, record)?
Yes would have to have a look how that best integrates with your work once we are putting it together...

2021-09-09 04:50 UTC, wlthomson commented on src/util/sync/translation/item.rs
> +    async fn test_item_translation() {
> You would basically have the same test case twice, wouldn't you? for this reason I find it easier to do it in one pass...

My understanding is that a unit test just focuses on one method or function and are don't need to be aware of the greater context except perhaps in providing a good coverage of inputs, i.e. a unit test is isolated and stateless (at least as much as possible), it passes if a given input returns the expected output. In comparison, integration tests are used to test that multiple methods (which are already tested in isolation to ensure they work individully) also behave as expected when used together. Typically unit tests are great in number so that they test as many function "branches" as possible, whereas integration tests are more sparse and designed for additional reassurance that the components which we know work as expected in isolation also behave as expected when combined. For that reason, I think it's quite OK for them to overlap in some instances, in fact I think the coverage provided by unit tests is complementary as it allows the integration tests to assume correctness of the functions they are testing in combination.

2021-09-09 04:51 UTC, andreievg commented on src/util/sync/translation/item.rs
> +    async fn test_item_translation() {
I am happy with just one test. But shouldn't it be in RepositorySync ? A bit weird to me to import the consumer of the scoped method. 
Anyways also happy to keep it as is, and see how it looks further down the road. So not stopping approval of PR

2021-09-09 05:00 UTC, wlthomson commented
> 
> 
> > After another discussion with Will we realized that Andrei and me probably planted to use something more closer to a DAO pattern and that DAO and repository pattern are complimentary (e.g. [baeldung.com/java-dao-vs-repository](https://www.baeldung.com/java-dao-vs-repository)). For this reason I did some experimenting using a DAO layer between ORM and Repository where the Repository layer is mostly independent from Diesel and only uses the DAO layer
> 
> I am glad you didn't, because I would have disagreed, two layers of abstraction ORM, and DOA/Repo type is plenty for what we are trying to build.
> 
> Also can you please include me in these sorts of discussions.
> 
> @wlthomson I skimmed through your post, didn't really read it, since we already made a decision. Didn't want to be distracted (wanted to actually focus on getting some work done)
> 
> > Anyways, will get on with a proper review now
> 
> Would recommend that you submit a PR first, I can do the review for this one

There was no discussion, except for Clemens posting that article and asking me if it was representative of what I was trying to say in the meeting (it is). The problem is that this PR includes logic for inserting records into the db directly without the buffer, so there is a lot of overlap which will need resolving. If we prefer to do the PR anyway, I'll do that.

2021-09-09 05:07 UTC, andreievg commented on src/database/repository/diesel/sync.rs
> +    pub async fn integrate_records(
> we expect buffering to work with it.
@wlthomson have you read this design and diagram https://github.com/openmsupply/org-issues/discussions/32 ?

> And have you had a look at description of the issue you are working on ?

https://github.com/openmsupply/remote-server/issues/278

It just involves saving and writing to buffer (nothing more)

then this issue: 

https://github.com/openmsupply/remote-server/issues/279

will store incoming sync record in the buffer.

then `import_sync_records` would either get an array of records or look them up in db one at a time and integrate them. it's pretty simple, if you having issue conceptualising it i think it's best to just follow the specs in the issue and you'll see how it all fits together when it's implemented.

2021-09-09 05:24 UTC, andreievg commented on src/util/sync/translation/item.rs
> +impl LegacyItemRow {
There is a `from` there, this translate also checks for name of the table, we might end up moving that though. And `from` doesn't take arguments, likely needed for complex translations, although that might be a seperate method.

> It also gives us conversion back from ItemRow to LegacyItemRow for free

No it doesn't (you have to implement seperate From<LegacyItemRow> for ItemRow and From<ItemRow> for LegacyItemRow)

![Screen Shot 2021-09-09 at 5 19 13 PM](https://user-images.githubusercontent.com/26194949/132627443-0d55a55e-7093-4c3f-b8a2-b58f189d9cff.png)

2021-09-09 05:25 UTC, andreievg commented on src/database/repository/diesel/sync.rs
> +                        NameRepository::upsert_one_tx(&connection, record)?
sync records are taken out of buffer, and integrated, pretty simple imo.

2021-09-09 05:26 UTC, wlthomson commented on src/database/repository/diesel/sync.rs
> +    pub async fn integrate_records(
I've read the issues, but I finding it hard to understand how this PR integrates with that design and how the sync buffer reading and writing is expected to be implemented (hence the relevance of the repo discussion).

I think it's best if I PR what I have so far and we can discuss there, as it might be more productive to get your direct thoughts on the code.

2021-09-09 05:42 UTC, wlthomson commented on src/util/sync/translation/item.rs
> +impl LegacyItemRow {
Ah, yeah you're right. I misunderstood what was being said here: https://doc.rust-lang.org/rust-by-example/conversion/from_into.html.

2021-09-09 05:46 UTC, wlthomson commented on src/database/repository/diesel/sync.rs
> +                        NameRepository::upsert_one_tx(&connection, record)?
Is the buffer the sane as what you've called `central_queue` on the diagram?

2021-09-09 06:18 UTC, wlthomson commented on src/database/repository/diesel/sync.rs
> +#[derive(Clone)]
Does it? I thought it returned a reference to the same repository?

From `anymap::Map`:

```
/// Returns a reference to the value stored in the collection for the type `T`, if it exists.
#[inline]
pub fn get<T: IntoBox<A>>(&self) -> Option<&T> {
  self.raw.get(&TypeId::of::<T>())
  .map(|any| unsafe { any.downcast_ref_unchecked::<T>() })
}
```

Although, `AnyRepository` includes the `CloneAny` trait, so maybe you're right? I think the cloning of the pool may be implemented with reference counting under-the-hood (@chris-morgan)?

In any case, I'm wondering if it might be a good idea to take the pool out of the repos and inject it into the methods instead (like has been done for the `_tx` methods here? Also something for later, perhaps.

2021-09-09 06:26 UTC, wlthomson commented
> After another discussion with Will we realized that Andrei and me probably planted to use something more closer to a DAO pattern and that DAO and repository pattern are complimentary (e.g. [baeldung.com/java-dao-vs-repository](https://www.baeldung.com/java-dao-vs-repository)). For this reason I did some experimenting using a DAO layer between ORM and Repository where the Repository layer is mostly independent from Diesel and only uses the DAO layer
> 
> I am glad you didn't, because I would have disagreed, two layers of abstraction ORM, and DOA/Repo type is plenty for what we are trying to build.

That's fine, but it's unclear to me what a DAO/Repo is and what logic goes where?

> @wlthomson I skimmed through your post, didn't really read it, since we already made a decision. Didn't want to be distracted (wanted to actually focus on getting some work done)
> 
> Also can you please include me in these sorts of discussions.

I'm trying to understand what that decision was, and I'm asking because it's a blocker on the buffer work.

There was no big discussion, it consisted of Clemens posting that article and asking me if it was representative of what I was trying to say in the meeting and me saying it was. My question is just so I can have that decision in written form so that I know how to move forward with buffer translation logic. I don't really know what the decision was and it's unclear from this PR the scope of `SyncRepository` and whether it will also be used for e.g. reading and writing buffer records.

2021-09-09 06:43 UTC, chris-morgan commented on src/database/repository/diesel/sync.rs
> +#[derive(Clone)]
The use of a cloneable AnyMap seems to already be a historical artefact—it’s not actually doing any cloning; you can change AnyRepository from CloneAny to Any and it works fine.

2021-09-09 07:19 UTC, clemens-msupply commented on src/database/repository/diesel/item.rs
> +        let q = diesel::sql_query(query)
Fixed in f8885b

2021-09-09 07:20 UTC, clemens-msupply commented on migrations/postgres/00000105_create_item_table/up.sql
> +CREATE TYPE item_type AS ENUM ('general', 'service', 'cross_reference', 'none_stock');
Removed item type in d8cc52

2021-09-09 07:20 UTC, clemens-msupply commented on src/database/repository/diesel/item.rs
> +        ItemRepository::insert_one_tx(&connection, item_row)?;
Slipped into f8885b

2021-09-09 10:45 UTC, wlthomson commented on src/database/repository/diesel/sync.rs
> +                        NameRepository::upsert_one_tx(&connection, record)?
EDIT: `central_queue` is equivalent to `central_buffer_queue`. Resolves most of my immediate confusion.

2021-09-09 10:45 UTC, wlthomson commented on src/util/sync/translation/item.rs
> +}
Not a big deal, resolving as don't want to add unhelpful blockers.

2021-09-09 10:52 UTC, wlthomson commented on src/database/repository/diesel/sync.rs
> +    pub async fn integrate_records(
Thanks for the review @andreievg, resolving this now.

2021-09-09 10:59 UTC, wlthomson commented on src/database/repository/diesel/sync.rs
> +#[derive(Clone)]
> 
> 
> The use of a cloneable AnyMap seems to already be a historical artefact—it’s not actually doing any cloning; you can change the definition of AnyRepository from CloneAny to Any and it works fine (and so this should be done).

Cool, thanks. So, to clarify (for my own learning if nothing else), is this unrelated to the cloning @andreievg is referencing, or are you saying that `repository.get` in fact isn't doing any cloning and so there will be no functional difference in removing the trait?

2021-09-09 11:13 UTC, chris-morgan commented on src/database/repository/diesel/sync.rs
> +#[derive(Clone)]
`registry.get()` doesn’t clone and never did; the reason it used to need CloneAny was because the registry needed to be Clone because we were using a registry per thread (so it cloned each item in the registry at thread creation time only), but now use just one system-wide. See https://github.com/openmsupply/remote-server/pull/219#discussion_r671918062 and 024719867e62aeebaace8cfba44b2df444eb3e93.

2021-09-09 11:29 UTC, wlthomson commented on src/database/repository/diesel/sync.rs
> +#[derive(Clone)]
Ah, right. I can understand the confusion, I should have removed `CloneAny` in 0247198. Will make an issue.

2021-09-09 12:00 UTC, wlthomson commented on src/database/repository/diesel/item.rs
> +        ItemRepository::insert_one_tx(&connection, item_row)?;
Note: you probably already know this, but if you paste a commit hash before pushing the commits, github won't generate a link. When this happens to me, I edit the comment after pushing the relevant commits. The commit link should be generated after doing that 🤞.

2021-09-09 12:05 UTC, andreievg approved these changes
Thanks for changes and answers!
Just realised there is still a couple of unresolved comments, but they dont' look that important, up to you if you want to make the changes or not

2021-09-09 19:57 UTC, clemens-msupply commented
thanks for the review!

> That's fine, but it's unclear to me what a DAO/Repo is and what logic goes where?

A DAO/Repo is a minimal layer over the DB. This has the advantages:
- all low level db and orm code is in one place and doesn't leak into the rest of the code base
- You can (easier) do cool stuff like: swap DBs, access a DB over the network, request caching, logging... all in a transparent way.
If you put logic in it you water down these advantages and your Repositories just becomes "normal" code.

2021-09-10 00:12 UTC, andreievg commented
@wlthomson can you review changes requested please, good to merge soon

2021-09-10 01:11 UTC, wlthomson approved these changes

2021-09-10 01:13 UTC, merged