#278 add central queue
openmsupply/remote-server pull request #315
Opened 2021-09-09 05:51 UTC by wlthomson

WIP for adding central queue (sync buffer) table.

2021-09-09 06:00 UTC, wlthomson commented on src/main.rs
> +    database::{
I think some of this stuff overlaps with #283, can be removed and potentially cherry-picked in another branch?

2021-09-09 08:14 UTC, andreievg requested changes
Thanks Will, a few changes please, and overall comment:

We should stick to scope of issue that's being implemented: https://github.com/openmsupply/remote-server/issues/278

Also if there are some question about naming etc, it's good to have a discussion in the issue. 

Sqlite doesn't support batch insert, diesel made a work around by doing them in a transaction, but I think that requires SqliteConnection vs pooled one, i'll have a look now

2021-09-09 08:15 UTC, andreievg requested changes

2021-09-09 08:15 UTC, andreievg commented on src/database/repository/diesel/sync_buffer.rs
> +            .expect("");
just noticed, no panics please

2021-09-09 08:48 UTC, wlthomson commented on src/database/repository/mock/item.rs
> +            _ => Err(RepositoryError::DBError {
Agree. Branched before agreed to close that PR. Have cherry-picked it out.

2021-09-09 09:48 UTC, wlthomson commented on src/main.rs
> +    database::{
Reverted changes to `main.rs`. As noted in ba3cefb3b6180588fb70e1235ffc0291c9d80394 reverted changes may still be useful later as a reference for #283.

2021-09-09 09:52 UTC, wlthomson commented on src/database/schema/mod.rs
> +    SyncBuffer(SyncBufferRow),
True. Now it's there I don't think there is much utility in removing it in isolation at this point? Will remove all this in #312, anyway.

2021-09-09 10:12 UTC, wlthomson commented on src/database/schema/sync_buffer.rs
> +#[derive(Clone, Queryable, Insertable, Debug, PartialEq, Eq)]
Much nicer, but note that this is a bit of an outlier in that it's not involved in the graphql schema. Removing the `Clone` trait implementation works fine here (given that 'DatabaseRow' enum is removed), but I don't think it's as simple for the other types, unfortunately.

2021-09-09 10:26 UTC, wlthomson commented on src/database/schema/sync_buffer.rs
> +#[derive(Clone, Queryable, Insertable, Debug, PartialEq, Eq)]
83956184f3ddd4ab4d2b5068b6f91b9b6cefe6bf.

2021-09-09 10:27 UTC, wlthomson commented on src/database/schema/mod.rs
> +    SyncBuffer(SyncBufferRow),
Update: 83956184f3ddd4ab4d2b5068b6f91b9b6cefe6bf.

2021-09-09 10:30 UTC, wlthomson commented on src/database/repository/diesel/sync_buffer.rs
> +            .expect("");
d22257300a285b55e6ce6fa799e8ddd46fb28857.

2021-09-09 10:35 UTC, wlthomson commented on src/main.rs
> +          sync_receiver.listen(&sync_connection, &sync_buffer_repository).await;
Removed this as out-of-scope, but commit history can be referenced for #279 if it remains helpful.

2021-09-09 10:36 UTC, wlthomson commented on src/util/sync/mod.rs
> +    pub async fn pull_queued_records(
Yup, reverted (and as above can be referenced or cherry-picked from commit history if and when needed).

2021-09-09 11:23 UTC, andreievg commented on src/database/repository/diesel/central_sync_buffer.rs
> +            .execute(&connection)?;
this doesn't compile in sqlite, needs explicit type casting to connection (as there are some issues with pooled connection for sqlite, since queries are batched manually:

```rust
      let connection: &DBBackendConnection = &&get_connection(&self.pool)?;
        diesel::insert_into(sync_buffer)
            .values(sync_buffer_rows)
            .execute(connection)
            .expect("");
        Ok(())
```

2021-09-09 11:23 UTC, andreievg commented on src/database/repository/diesel/central_sync_buffer.rs
> +}
a couple of test would be great

2021-09-09 11:25 UTC, andreievg requested changes
looks good, just one compilation error and a test, would be great

2021-09-09 12:13 UTC, andreievg commented on src/database/repository/diesel/central_sync_buffer.rs
> +            .execute(&connection)?;
actually much cleaner to use fully qualified syntax for deref
```rust
let connection = &get_connection(&self.pool)?;
diesel::insert_into(sync_buffer)
            .values(sync_buffer_rows)
            .execute(Deref::deref(connection))
```

2021-09-09 12:24 UTC, chris-morgan commented on src/database/repository/diesel/central_sync_buffer.rs
> +            .execute(&connection)?;
For myself at least, I’d *never* write calls to `deref` or `deref_mut` manually; I’d prefer `&*connection`. But taking all into account, I believe this should work (though I haven’t tried it):

```rust
let connection = get_connection(&self.pool)?;
diesel::insert_into(sync_buffer)
            .values(sync_buffer_rows)
            .execute(&connection)
```

2021-09-09 12:26 UTC, chris-morgan commented on src/database/repository/diesel/central_sync_buffer.rs
> +            .execute(&connection)?;
Incidentally also, `Deref::deref` is not fully qualified; fully qualified is `<Type as Trait>::method`; `Type::method` and `Trait::method` are both partially qualified.

2021-09-09 13:05 UTC, andreievg commented on src/database/repository/diesel/central_sync_buffer.rs
> +            .execute(&connection)?;
Thanks @chris-morgan, `&**connection` works well (@wlthomson, can we use that one), I've spent too long trying to figure this out lol, it needs to be cast explicitly to SqliteConnection, there is some trickery that diesel does with sqlite for batched queries (manual batches them in a transaction, some unmet bound). I couldn't really figure it out, but `&connection` doesn't work, if you want to play around (
[checkdiesel.zip](https://github.com/openmsupply/remote-server/files/7136679/checkdiesel.zip)), 30 lines of code to demonstrate it.

Thanks for clarifying about fully qualified.

Can i ask, what is below called ? I can't remember, I read it somewhere but can't remember the name or can't thin of keyword to google it (been playing around with proc_macros, and it's useful to avoid importing traits)
```rust
RunQueryDsl::<DBBackendConnection>::execute(
            diesel::insert_into(sync_buffer).values(sync_buffer_rows),
            &connection,
        )?;
```
btw DBBackendConnection is either PgConnection or SqliteConnection based cfg feature flag.

2021-09-09 23:01 UTC, chris-morgan commented on src/database/repository/diesel/central_sync_buffer.rs
> +            .execute(&connection)?;
It’s a type inference thing. The referencing operator `&` *is* capable of dereferencing first when needed, but the problem here is loosely that it doesn’t think it needs to, because `PooledConnection<ConnectionManager<SqliteConnection>>` satisfies what `execute` is looking for in its type parameter `Conn` (a reference to some type that implements the `Connection` trait), and so when that fails in a *different* way (because the connection actually isn’t sufficient for it because of the lack of `BatchInsert`), it doesn’t try any other combinations (because that way lies madness and slow compilation). So you need to manually dereference it first (something that isn’t required terribly often).

----

As for `Type::method(receiver, arg)` versus `receiver.method(arg)`, that used to be called [universal function call syntax](https://doc.rust-lang.org/1.30.0/book/first-edition/ufcs.html), but is now called [fully qualified syntax](https://doc.rust-lang.org/book/ch19-03-advanced-traits.html#fully-qualified-syntax-for-disambiguation-calling-methods-with-the-same-name), crucially no longer including *function call* in the name (since you can use the syntax to take a reference to a method or to use an associated constant), but it seems to be fuzzy about what “*fully* qualified” means, so I’m seeking clarification in https://github.com/rust-lang/rust/issues/88799. (As a matter of simple fact, `Type::method` and `<Type>::method` are *not* fully qualified unless there’s a matching inherent method: otherwise it’ll look through trait implementations.)

----

On naming, incidentally, Rust convention would have `DbBackendConnection` (*c.f.* `PgConnection`, `SqliteConnection`, `RunQueryDsl`). Up to you lot whether you go that way or not.

2021-09-10 00:13 UTC, andreievg commented on src/database/repository/diesel/central_sync_buffer.rs
> +            .execute(&connection)?;
Thanks very much @chris-morgan, very good explanation

2021-09-10 00:15 UTC, andreievg commented
@wlthomson a couple of changes please, `test` and explicit deref coercion of connection in `insert_many` (so that feature sqlite compiles)

2021-09-10 02:15 UTC, wlthomson commented on src/database/repository/diesel/central_sync_buffer.rs
> +            .execute(&connection)?;
7ec0efd.

2021-09-10 02:15 UTC, wlthomson commented on src/database/repository/diesel/central_sync_buffer.rs
> +}
8e9903f.

2021-09-10 08:28 UTC, wlthomson commented
@andreievg Should be ready to go.

2021-09-10 15:16 UTC, andreievg commented on tests/repository/basic.rs
> +            data: "{ \"ID\": \"store_a\" }".to_string(),
r#"{ "ID": "store_a" }"#

2021-09-10 15:18 UTC, andreievg approved these changes
Awesome, thanks Will ! There is one suggestion, but not required

2021-09-11 06:00 UTC, wlthomson commented on tests/repository/basic.rs
> +            data: "{ \"ID\": \"store_a\" }".to_string(),
a12eed8.

2021-09-11 06:21 UTC, merged