#312 Remove AnyRepository trait AnyClone
openmsupply/remote-server pull request #322
Opened 2021-09-11 08:51 UTC by wlthomson

Closes #312.

2021-09-12 21:53 UTC, clemens-msupply approved these changes

2021-09-12 22:56 UTC, andreievg requested changes
can you also remove all of the clones for repositories

2021-09-13 00:56 UTC, wlthomson commented
> 
> 
> can you also remove all of the clones for repositories, please

Sigh, that was kind of the whole point, not sure how I forgot that! 3507467dc995ab5ca57c4bae1fcff31027bea5cb.

2021-09-13 00:57 UTC, andreievg approved these changes
thanks

2021-09-13 04:38 UTC, merged