Flagless DB target differentiation
openmsupply/remote-server pull request #323
Opened 2021-09-12 11:15 UTC by andreievg

This is out of scope for M1, but it's done in my own time. Please have a look.

Actually ended up being less code (but that's probably due to cleaning up existing 'wet' code). Also removed the need to use `Clone`

### Motivations

I didn't like using cfg flags to differentiate between connection types, main concern:
* not being able to see compilation errors for both targets at the same time. 
* needing to set flags in dev environment (and change between them to see if compiles for both targets).
* i think it's hard to read code behind cfg flags, and I think if they are used they should be used at entry point, but since we have target specific queries they will be scattered throughout the code
* would like to see a test for both DB's run at once.

### How does the this way work ?

Differentiate between database with enum, and create a wrapper for both pool and pooled connection, this would of course mean we would have to do the following:

``` rust
// let query = ...;

match connection_wrapper.db_type {
   Sqlite(connection) => query.execute(connection),
   Pg(connection) => query.execute(connection)
}
```

this is done with macros, i.e.:

```rust
macro_rules! execute_pool {
    ($pool:expr, $query:expr) => {
        match $pool {
            crate::database::repository::DbConnectionPool::Sqlite(_) => $query
                .execute(&*$pool.get_sqlite_connection()?)
                .map_err(|err| RepositoryError::from(err)),
            crate::database::repository::DbConnectionPool::Pg(_) => $query
                .execute(&*$pool.get_pg_connection()?)
                .map_err(|err| RepositoryError::from(err)),
        }
    };
}
// ....

// let query = ...;
execute_pool!(pool_wrapper, query)?
```

### Review suggestion

have a look at: `repository/database_wrapper` code.

and check out how it's used in `diesel/item.rs` (or any other repository)

### Extras

We can possibly use generic to achieve the same thing, but it would be much harder and code would be a lot more complex.

I think changes in this PR will save developers a bit of time overall.

If you are happy with it, we can talk about merging this in in strategic way (to reduce load of conflicts in existing PRs)

2021-09-14 02:40 UTC, wlthomson reviewed
Took me a while to figure out everything going on here!

I think this PR can be split into two separate parts: the enum and the macros. Generally, like the idea of using an enum and having the ability to catch compilation errors etc. with a single build/test. The only bit I'm not sure I'm convinced by yet is the argument that the macros here are easier to work with that cfg flags.

AFAICS, the macros aren't really reducing the extent to which cfg flags are scattered through the code (which I think is the motivation that applies from those listed in the PR description), but is instead hiding them behind multiple nested macros. Personally, I find this makes the code a bit harder to understand, especially when the macros involve matching on parameters and cfg flags (for example, it looks like the `execute_connection` macro branches three levels deep, with each level involving pattern matching on parameter count, connection type and cfg flags, respectively).

In general, I like the enum idea and the substituting of placeholder structs to avoid having to pull in unneeded dependencies, but I would be interested in if you have any thoughts on whether the amount of macros here could be reduced?

EDIT: @chris-morgan you were involved in the original "alternate definition" approach, so would also be interested in any thoughts you might have?

2021-09-14 04:04 UTC, clemens-msupply commented
cool, yes the build cfg flags are a bit annoying. Furthermore, with this approach we can support sqlite and pg in the same binary (and remove the build feature flag altogether?).

Also have concerns about macros, having them in our code base makes the Rust code even more complex... 

The only alternative I see is to use traits and and dynamic dispatch (which is kind of needed for the Repo pattern ;-) ). But Will said you already tried that? Diesel's trait definitions makes it unnecessary hard as well but, just for reference, I think Chris got a generic Connection type working: https://github.com/openmsupply/remote-server/blob/playing-with-types/src/database/repository/diesel/item_line.rs

2021-09-14 04:37 UTC, wlthomson commented
> 
> 
> cool, yes the build cfg flags are a bit annoying. Furthermore, with this approach we can support sqlite and pg in the same binary (and remove the build feature flag altogether?).

Probably still want the build flag to produce separate binaries and avoiding bloating the sqlite binary with pg dependencies and vice-versa. One of the things I like about the enum approach and the "placeholder" db structs is that it allows for this (I imagine that's the intention). The bit I'm curious about is how much the above (which I think is pretty cool and clever) can be retained while removing some of the more compex macros (if I understand correctly, I think some of them are required for the placeholder struct stuff to work, but some of them are more high-level semantic sugar which might be able to be reduced a bit).

2021-09-14 04:37 UTC, andreievg commented
@clemens-msupply @wlthomson thanks for taking a look, changing this to draft, and putting it on back burner. Sorry even though i realised this could be a distraction from M1, but still wanted to play around with possible solutions. I'll do a little bit more on the weekend. 

Only comment for now

Yep it adds complexity (but not in the consumption of macros), but still i guess it's something to maintain. We consume complex code all the time btw, diesel Insertable, Queryable derive on one derived schema table (with just an ID field) is 1000 lines of derived complex code (but I guess it's something for diesel to maintain, so technically doesn't count)

2021-09-14 06:10 UTC, chris-morgan requested changes
After much reflection, and with all the stuff I’ve mentioned taken into account, I think this is probably the best way forwards, though it’ll probably take a bit of time to settle some details. I’m fairly sure that trait objects won’t work out (I can explain why if it’s unclear), and generics require a bit more involved work in the bifurcated cases—it’s definitely possible, and not even particularly painful, but the macro approach is certainly syntactically cleaner. It would be unlikely to be *too* much work to migrate from one style to the other.

I’m interested in taking this further and tidying and polishing it all up, if you’d like me to.

2021-09-14 06:10 UTC, chris-morgan commented on src/database/repository/diesel/database_wrapper/mod.rs
> +    Pg(PgPool),
(I write this comment last of all; it at least partly invalidates some of my earlier comments, though it fits in with others like my remark on shifting where panicking occurs.)

I think that it would be better to simply remove all traces of Pg/Sqlite support at compile-time if not applicable: `#[cfg(feature = "postgres")] Pg(PgPool)`, *&c.* I can’t see any obstacles to this working, it should be much of a muchness for writing code and it will definitely optimise single-DB-mode (which is, I believe, how you expect to deploy) better.

2021-09-14 07:13 UTC, clemens-msupply commented
> I’m fairly sure that trait objects won’t work out (I can explain why if it’s unclear)

yes please

Other question, are macros needed at all? can't we just do the same with helper functions?

2021-09-14 14:59 UTC, andreievg commented
@chris-morgan, thanks very much for your comments, i ran out of time today to address them. 

> I’m interested in taking this further and tidying and polishing it all up, if you’d like me to.

That would be great. I do want to reply to a couple of comments you've made though, i had a quick look through them, and want to expand on a couple of your suggestions and make a note of areas of this PR that i don't like

2021-09-15 02:38 UTC, chris-morgan commented
Trait objects won’t work out because associated types must match, which would mean that you’d be needing to use trait objects at more than one level (connection → backend → query builder + bind collector), but you can’t do that because of the nature of associated types as distinct from generics, that they’re *output* types and up to the *implementer* to decide, rather than input types like generics—so you can’t say `dyn Connection<Backend=Box<dyn Backend<…>>>` because `PgConnection` says it works on a `Pg` backend, not a `Box<dyn Backend<…>>`. So in order to work around *that* you’d need to define your own types and traits to cover the desired functionality, and you’d honestly be reimplementing half of Diesel before long. I mildly suspect object safety might bite you somewhere along the way too and scuttle the entire endeavour. And once you’re heading in that direction, you’d very probably find it easier to do it with a stack of enums and implementing the required traits that way—essentially manually-implemented dynamic dispatch.

> Other question, are macros needed at all? can't we just do the same with helper functions?

Macros are necessary because we need to remove the code for a disabled database because the stuff it depends on from Diesel *doesn’t exist*. If you don’t understand, try removing the `not(feature = "postgres")` postgres_operation implementation and un-cfg the other, and watch it fail to compile.

You *could* get around this by defining a dummy `PgConnection`, `Pg`, *&c.* which all implement the same traits as Diesel’s versions of them, but I reckon using macros is the wiser approach.

2021-09-15 04:41 UTC, andreievg commented on src/database/repository/diesel/database_wrapper/macros.rs
> +            crate::database::repository::DbConnectionPool::Sqlite(_) => {
ohh i didn't know about this one, cheers ! (I think I need to read the 1.5 book, new one lacks some very good details that 1.5 provides)

2021-09-15 04:45 UTC, andreievg commented on src/database/repository/diesel/database_wrapper/macros.rs
> +            .map_err(|err| RepositoryError::from(err))
.map_err(RepositoryError::from) -> that's nicer, I didn't realise we can use methods for closures, great.

wanted `?` to be handled outside of macro, and there are a couple of consumers of the macro that return the same Result but with just different error, so wanted to avoid needing `Ok(operation..?)`, and just do `operation...`, this kind of couples macro with repository error though, so  probably `Ok(opeartion..?)` would be better.

2021-09-15 04:45 UTC, andreievg commented on src/database/repository/diesel/database_wrapper/mod.rs
> +    pub fn clone(&self) -> DbConnectionPool {
Just lack of experience, clone is much nicer thanks

2021-09-15 04:46 UTC, andreievg commented on src/database/repository/diesel/database_wrapper/mod.rs
> +        panic!("postgres flag is not enabled")
> The code would be made briefer and subjectively nicer by shifting the cfg stuff inside the method.

that's much better thanks (I remember getting some `experimental` warning when using flags inside methods, but I can't replicate it now, I must have got something confused)

> You can write it in other styles too:

Ohh thanks. Although i think second and third example might cause compilation error if pool.get is not a valid method

2021-09-15 04:46 UTC, andreievg commented on src/database/repository/diesel/database_wrapper/mod.rs
> +    pub fn get_pg_connection(&self) -> Result<PgPooledConnection, RepositoryError> {
oki, i get it : ). good point will try and stick to that

2021-09-15 04:46 UTC, andreievg commented on src/database/repository/diesel/database_wrapper/mod.rs
> +    }
True, agree. I wasn't happy about this, although i am not sure what you mean about panic shifted to `new`.

2021-09-15 04:46 UTC, andreievg commented on src/database/repository/diesel/database_wrapper/mod.rs
> +pub type PgConnection = std::marker::PhantomData<bool>;
I completely forgot that `()`, and was obviously lazy to not research. Thanks for explaining about PhantomData, I've used it only once previously in structure definition, types that are used in implementation but are not in structure fields. (in a personal project, it was something like `struct ScalarString<Type, PgType, SqliteType> { value: Type, db_types: PhantomData<PgType, SqliteType }`

2021-09-15 04:46 UTC, andreievg commented on src/database/repository/diesel/database_wrapper/macros.rs
> +    // How to match all ?
great, cheers

2021-09-15 04:58 UTC, andreievg commented on src/database/repository/diesel/database_wrapper/macros.rs
> +                    &*$pool.get_sqlite_connection()?,
Thanks for explanation
true `$pool` should indeed be indent

but the reason behind calling `get` on `$pool` vs `pool` was that pool might be replaced with something other then `Pool` (if flag is not targeting that DB), and `.get()` method will not exist on the pool. I could have been better at structuring this whole thing to avoid it though, cheers for pointing out the inefficiency here.

2021-09-15 04:59 UTC, andreievg commented on src/database/repository/diesel/database_wrapper/macros.rs
> +        panic!("postgres flag is not enabled")
true, I think you'll do it even better (looking at your last comment), and remove the need to even get here if flag is not present

2021-09-15 04:59 UTC, chris-morgan commented on src/database/repository/diesel/database_wrapper/mod.rs
> +    }
I mean that the cfg variation would be shifted to the `new` method:

```rust
    pub fn new(settings: &Settings) -> DbConnectionPool {
        match settings.database.database_type {
            #[cfg(feature = "postgres")]
            ConnectionType::Pg => DbConnectionPool::new_pg(&settings.database.connection_string()),
            #[cfg(not(feature = "postgres"))]
            ConnectionType::Pg => panic!("postgres flag is not enabled"),
            …
        }
    }
```

(As for whether `new_pg` should then exist at all, well, that’s another matter. I’m inclined to inline it unless there’s a compelling reason for it to exist.)

2021-09-15 05:03 UTC, chris-morgan commented on src/database/repository/diesel/database_wrapper/mod.rs
> +        panic!("postgres flag is not enabled")
True, I had forgotten it would be absent then. Change `_ if cfg!(feature = "postgres")` to `#[cfg(feature = "postgres")] _`, then. Not actually sure why I didn’t suggest that.

Attributes on blocks and match branches are comparatively recent in the scheme of things, but more than a few months. Attributes on *expressions* is still unstable, and that’s probably what you hit.

2021-09-15 05:14 UTC, andreievg commented on src/database/repository/diesel/database_wrapper/macros.rs
> +    ($connection:expr, $postgres_query:expr,$sqlite_query:expr) => {
Ohh wow, thanks, I would never have learned this. Much better

2021-09-15 05:15 UTC, chris-morgan commented on src/database/repository/diesel/database_wrapper/macros.rs
> +            .map_err(|err| RepositoryError::from(err))
`map_err` takes any parameter that implements `FnOnce(E) -> F`, `FnOnce` meaning a function that can be called once, but might not be able to be called multiple times. That covers closures that consume any variables they capture, and any other function types that don’t close over any variables (because they don’t have any internal state to cause trouble by being called multiple times), which includes some closures, all functions and all safe function pointers.

2021-09-15 05:21 UTC, chris-morgan commented on src/database/repository/diesel/database_wrapper/macros.rs
> +                    &*$pool.get_sqlite_connection()?,
The use of the DB-specific operation macro takes care of that, so that it’ll discard the `$operation` it receives in that case.

2021-09-15 05:26 UTC, andreievg commented on src/database/repository/diesel/database_wrapper/macros.rs
> +macro_rules! execute_pool {
> If you really want the many macros, you could consider generating the macros with a macro. Yep, macro currying totally works:

lol i actually contemplated this, but didn't want to scare the team. Same reason really for duplicating macros, thought i would be too foreign to specify method name as ident in macro invocation. I guess macro generating macro can work, although now that I see the new matching syntax, I would imagine that repetition may seem less cumbersome:

```rust
macro_rules! load_pool {
        ($($args:tt)*) => {
            $crate::database::repository::macros::op!($($args)*, load)
       };
}

```

idk, really up to you, but would be nice not to have method name as parameter for end consumer of macro

2021-09-15 05:35 UTC, chris-morgan commented on src/database/repository/diesel/database_wrapper/macros.rs
> +    ($connection:expr, $postgres_query:expr,$sqlite_query:expr) => {
Structural macros (`macro_rules!`) are just defining the syntactic structure they expect to match against. If you don’t have a good reason to do otherwise then making them look function-like is often a good choice, but you can make them match just about anything you like (the exception being things that could be ambiguous, e.g. you can’t have an expr followed by a dot because the expr would like to consume the dot). If you want to see some of the extents you can go to with just structural macros, take a look at [`diesel::table!`](https://docs.diesel.rs/src/diesel/macros/mod.rs.html#264-276), which uses a fairly complex [*tt muncher*](https://veykril.github.io/tlborm/decl-macros/patterns/tt-muncher.html).

2021-09-15 05:44 UTC, andreievg commented on src/database/repository/diesel/item.rs
> +            connection,
Interested to hear what you mean (or you can just show it when you refactor this thing).

I would imagine if this trait is implemented for `Pool<ConnectionManager<PgConnection>>`,  `Pool<ConnectionManager<SqliteConnection>>`, `PgConnection` `SqliteConnection`, could work :
```rust
trait ToBaseConnection {
    fn sqlite_connection(&self) -> Result<SqliteConnection, RepositoryError>
    fn pg_connection(&self) ->  Result<PgConnection, RepositoryError>
}
```
of course PgConnection and SqliteConnection just Ok(self), and Pool would .get() and coerce.

2021-09-15 05:45 UTC, andreievg commented on src/database/repository/mod.rs
> +    // Connection doesn't exist
I think this will be removed by what you suggest below

2021-09-15 05:45 UTC, andreievg commented on src/database/repository/diesel/database_wrapper/mod.rs
> +    Pg(PgPool),
Yes please, those panics shouldn't be reachable at all

2021-09-15 06:05 UTC, andreievg commented
@chris-morgan, I managed to go through all of your comments, thanks again.

Yep it would be great if you can take this over, please, if you have the time.

Just a couple of notes
* Feel free to take over this branch or start your own from main (I mean there is no attachments to this work from my end)
* Conflict resolution at the end of it might be time consuming, we can do that btw (an we will be adding new repositories and adding to the existing in the meantime, just to say there will be a few conflicts)
* We are working on a deliverable (aimed at 27th of September), which doesn't have this in scope, so review of your work (not to say it will need a review, but we need to understand it), might be delayed until then (i'll be able to check it on the weekend or after working hours though, but don't expect the same from the rest of the team).

And just to make sure we are aligned:
* default features set is both DB's (although entry point for executable will only ever use one, tests will use both, and compilation problems should be evident without changing feature from default)
* can of-course build and test with individual DB targets. 

On that last spec, I would assume we would change our testing slightly to do something like below (we should be able to do that no problems I think, just want to make you aware of it).. might even do that bit without macro

```rust
async  test_it(con: DbConnectionWrapper) {
// the test
}

#[runtime::test]
async fn test_it_pg() {
test!(TestDatabaseProvider::new_pg(), test_it)
}

#[runtime::test]
test!(TestDatabaseProvider::new_sqlite(), test_it)
}
```

`test!` would `assert!(true)` if flag is missing

2021-09-15 09:33 UTC, andreievg commented on src/database/repository/diesel/database_wrapper/macros.rs
> +    ($connection:expr, $postgres_query:expr,$sqlite_query:expr) => {
cheers, that's great reference for token tree navigation of struct definition

2021-09-15 09:35 UTC, andreievg commented on src/database/repository/diesel/database_wrapper/mod.rs
> +    }
ohh soo much better

2021-09-15 11:21 UTC, chris-morgan commented on src/database/repository/diesel/item.rs
> +            connection,
It ends up more complicated than that, closer to `TryInto<DbConnection, Error = RepositoryError>`, because I’m making it so that `SqliteConnection` and `PgConnection` *don’t exist* when not compiled in. You *could* do it in more the style you describe, but it runs into more problems and I ended up deciding inversion was the most practical way of achieving it.

After implementing it all, I’m not sure about it. It’s kinda nice, but also kinda not nice. Meh. You decide.

2021-09-15 11:27 UTC, chris-morgan commented
I’ve implemented I think all of what I had in mind and added it onto this branch, and marked all the relevant points in this PR as resolved. `cargo test && cargo test --no-default-features --features=sqlite && cargo test --no-default-features --features=postgres` succeeds, and no warnings.

This can now sit for a while, or you can look at it and complain or ask questions or whatever, as you desire.

2021-09-16 03:45 UTC, andreievg commented
> This can now sit for a while, or you can look at it and complain or ask questions or whatever, as you desire.

@chris-morgan, thank you very much! Legend!

Will check it out over the weekend, and no doubt will have some question.

2022-02-17 03:32 UTC, andreievg commented
Sorry it's been so long, we ended up being quite busy during this period and had to de-priorities this, using macros for sorts and filter and still features flags for diesel query differences, hopefully we will have some time after V1 beta release end of March to revisit this.

Thank you very much for the changes to the original PR @chris-morgan, it's been useful and we definitely learned a thing or two from it.

2022-02-17 03:32 UTC, closed without merging