Add additional columns to item, name and store
openmsupply/remote-server pull request #325
Opened 2021-09-13 00:05 UTC by clemens-msupply

Add code, is_customer and is_supplier to existing tables

2021-09-13 01:06 UTC, andreievg commented on src/util/sync/translation/name.rs
> +    customer: bool,
i was hoping we can translate to is_customer and is_supplier here, would mean all our basic translations are in this struct definition. And the from becomes direct mapping. What do you think ?

2021-09-13 03:23 UTC, wlthomson requested changes
Mostly LGTM, just a minor re. the mock data and mirroring @andreievg re. being consistent with doing simple mappings on deserialisation.

2021-09-13 03:23 UTC, wlthomson commented on src/util/sync/translation/test_data/item.rs
>              id: "8F252B5884B74888AAB73A0D42C09E7F".to_owned(),
Can we add these to and import them from `src/database/mocks`?

Also, it's a lot easiser when dealing with mock data to have identifiers which are memorable and not prone to typos (especially when dealing with relational data with FK constraints). Can we follow the existing pattern of having meaningful identifiers like `item_row_a` rather than random UUIDs? Or, if we want to restrict our mock data to valid UUIDs, something like e.g. `"AAAAAA...AA"`, `"AAAAAA...AB"` etc.? UUIDs are uniformly distributed, so AFAICS there is no advantage to having meaningless UUIDs over human-readable ones (i.e. we are not making our mock data any better by avoiding using meaningful UUIDs).

If later down the road we want to implement UUID validation logic, we should then design mock data with a range of valid and invalid UUIDs specifically for that purpose. That's a separate deal than what we are testing here (and again, still should't use random UUIDs, anyway), so I don't think there's a reason to avoid adopting helpful UUIDs in the general purpose mock data?

2021-09-13 03:36 UTC, andreievg commented on src/util/sync/translation/test_data/item.rs
>              id: "8F252B5884B74888AAB73A0D42C09E7F".to_owned(),
@wlthomson you might have missed this PR btw: https://github.com/openmsupply/remote-server/pull/320

this data is coming directly from mSupply. I can see your point that there is a potential for typos (btw test shoulnd't pass if there is a typo), but there will be a lot of data here (like a record for every variation of enum), and copy paste like this might be the quickest way to do it. Also there is extra work of mocking UUIDS, why not just use actuall data ?

> If later down the road we want to implement UUID validation logic, we should then design mock data with a range of valid and invalid UUIDs specifically for that purpose

Are we going to validate UUIDs generated by central server ?

2021-09-13 03:38 UTC, andreievg commented on src/util/sync/translation/test_data/item.rs
>              id: "8F252B5884B74888AAB73A0D42C09E7F".to_owned(),
> especially when dealing with relational data with FK constraints

Another reason to use real data is to make sure those FK dependencies are met (we've already found a few cases while using real data where store 'name_id' is null or 'name_id' is specified but name record exists, so had to put extra conditions in translations to record ingore those special mSupply stores (which of course would have been missed if we were not using real mSupply data)

2021-09-13 06:59 UTC, clemens-msupply commented on src/util/sync/translation/name.rs
> +    customer: bool,
I think its better to stay closer to the original data struct to avoid confusion. We have to do one copy anyway to copy LegacyNameRow to NameRow.

2021-09-13 12:49 UTC, andreievg commented on src/util/sync/translation/name.rs
> +    customer: bool,
Hmm, but we are already translating fields with serde. Why do it in two places ?
I guess we can move it all to from, but then we would have to re-implement features that serde has out of the box (like enums conversions, defaults, error handling, validation, etc. (I guess we can use serde just for data type conversion, not field renaming, but to me, seeing it all in one place is less confusing)

I can't say I am a fan of duplication in from, there are ways to make it dry thought. And technically speaking we could actually put deserialise on Row rather then LegacyRow (but then it's hard to do more complex translations, where some fields need to be deserialised but don't go into Row, but are used in complex translation).

> We have to do one copy anyway to copy LegacyNameRow to NameRow.

Technically if we are translating in serde then it's not quite LegacyNameRow, but TranslatedNameRow. 

What do you think ?

2021-09-13 19:59 UTC, clemens-msupply commented on src/util/sync/translation/name.rs
> +    customer: bool,
We still need to convert to NameRow so why not stay explicit? We can still use serde to parse enums if needed... 

Is performance your concern?

2021-09-13 23:11 UTC, andreievg commented on src/util/sync/translation/name.rs
> +    customer: bool,
> Is performance your concern?

Not for sync

Have the same concern is you, code cleanliness (reducing confusion), in which case consistency is very important.

I guess I am ok to  moving renaming from serde and just use it for deserialising into correct data type, but not ok with having renaming in different places, so if we moving renaming then:
* make sure we have `from` for all LegacyRow -> Row (add it in LegacyItemRow and LegacyStoreRow), or move `from` to NameRow to `impl` of LegacyRow.
* remove renaming from derives

2021-09-14 01:54 UTC, andreievg commented on src/util/sync/translation/name.rs
> +    customer: bool,
what were the warnings that rename was fixing ?

2021-09-14 01:54 UTC, andreievg commented on src/util/sync/translation/name.rs
> +    customer: bool,
i guess I'll wait and see in a commit

2021-09-14 03:09 UTC, clemens-msupply commented on src/util/sync/translation/test_data/item.rs
>              id: "8F252B5884B74888AAB73A0D42C09E7F".to_owned(),
@wlthomson I think this can be resolved?

2021-09-14 03:47 UTC, andreievg approved these changes

2021-09-14 04:09 UTC, wlthomson commented on src/util/sync/translation/test_data/item.rs
>              id: "8F252B5884B74888AAB73A0D42C09E7F".to_owned(),
Yeah, can resolve. Might be worth making an issue to migrate the existing mock fixtures to the new way that test data is organised, though?

2021-09-14 04:14 UTC, wlthomson commented on src/util/sync/translation/name.rs
> +    customer: bool,
Since I agreed with @andreievg initial requested change, posting to say I also don't mind where it is done as long as it is consistent. The main benefit of renaming with serde is to keep the backend structs neat, i.e avoid having structs with `camelCase` fields etc, which I think will cause warnings as rust is quite strict on naming conventions.

2021-09-14 04:15 UTC, wlthomson approved these changes

2021-09-14 04:17 UTC, clemens-msupply commented on src/util/sync/translation/name.rs
> +    customer: bool,
I disabled the warnings for these "raw" data structs

2021-09-14 04:17 UTC, merged