#286 customer invoice mutation doc
openmsupply/remote-server pull request #333
Opened 2021-09-14 14:37 UTC by andreievg

Charge to 286

### Changes

* Added Customer Invoice mutation
* Add errors for customer invoice mutation
* Add ability to create anchors without them showing in the menu bar on the right side

(slight arrangements in upstream PR for supplier invoice mutation)

I didn't uphold my promise to try to shape BatchReductionBelowZero in a way it can be used to merge into front end state, suggestions welcome (i am not sure what that state is)

2021-09-16 08:39 UTC, joshxg requested changes
Great, thanks for this work! 😀 🎉 

My main comments:
- The differentiation between upsert and insert is confusing. It is made easier to distinguish between the differences if we use update and insert, with upsert being both. I think there is a lot of text that can be tided/removed if the type is a union as the distinction is then obvious.
- Some consistency in the error types would be helpful. I understand these are examples, but it would be good to ensure we can match errors at any level of the hierarchy for the required task. This would mean creating something like (obviously incomplete example):
![image](https://user-images.githubusercontent.com/35858975/133573874-13319bad-cb6e-4a68-b031-31e5e61f7824.png)

> I didn't uphold my promise to try to shape BatchReductionBelowZero in a way it can be used to merge into front end state, suggestions welcome (i am not sure what that state is)

The suggestion wasn't to know the state exactly, but to return errors in the same shape that the mutation was sent. 

For example, as I understand the return object would be:

```
[
    { code: ErrorCode.OtherPartyNameSomething, .. }, 
    { code: ErrorCode.BatchReductionBelowZero, .. }, 
    { code: ErrorCode.BatchReductionBelowZero, .. },
    { code: ErrorCode.BatchReductionBelowZero, .. }
]
```

The suggestion would just be that instead of an array, if the mutation that was sent was:

```
{
    id: "",
    lines: [ {id: "", .. } ]
}
```

Then essentially just adding an `error` property to any invalid object:

```
{
    id: ..
    error: { code: ErrorCode.OtherPartyNameSomething, .. }, 
    lines: [  { id, error: { code: ErrorCode.BatchReductionBelowZero, .. }}, ... ]
}
```

2021-09-17 00:01 UTC, mark-prins approved these changes
:+1: Awesome! thanks again @andreievg 

Had a couple of :nits - mostly though, Josh has beaten me to it and is asking the same sort of things. Main one is why there is the question of distinguishing between insert, update and upsert.

2021-09-20 23:48 UTC, andreievg commented on docs/content/docs/api/mutations.md
> +Mutations will happen sequentially if batched, an error will result in cancellation of mutation batch in which it originated and further mutation in the sequence will be discarded (but batched mutati
> I found this hard to read. Suggest:

updated [upstream](https://github.com/openmsupply/remote-server/pull/334) - f4d9b6b97065d4e841ee727c0afffa5ab91707f0

> I wonder how useful this form of batched mutation request is - it feels like an easy way to create invalid internal consistency. Either the mutations are related, in which case a transaction is better, or they aren't in which case it doesn't matter if one fails.

Agree. I don't know how to disable it (batching is a standard GraphQL feature that async graphql provides)

2021-09-20 23:49 UTC, andreievg commented on docs/content/docs/api/mutations.md
> +```
I think this is resolved in our convo about `InputObject` unions

2021-09-20 23:50 UTC, andreievg commented on docs/content/docs/api/mutations.md
> +    theirFerefence?: string,
i think this is fixed upstream, thanks for noting

2021-09-20 23:51 UTC, andreievg commented on docs/content/docs/api/mutations.md
> +    numberOfPacks: number
There is a concept of 'placeholder line' in customer invoices in mSupply, which don't have stockLineId (although stockLineId is compulsory in insert mutation, it's possible that this will be changed, maybe best to keep it ?)

2021-09-20 23:54 UTC, andreievg commented on docs/content/docs/api/custom_errors.md
> +  StockLineIdMissingInInvoiceLine =  "STOCK_LINE_ID_MISSING_IN_INVOICE_LINE"
Is the concern with bundle size or traffic ? 
* Bundle, how much extra does it add ?
* Traffic, seems like a very infrequent response ?
Either way I think while we deving, human readable might be a good way to go ?

2021-09-21 00:10 UTC, andreievg commented on docs/content/docs/api/custom_errors.md
> +}
I've update errors to be more hierarchical btw, here (maybe your comments is different now):  updated [upstream](https://github.com/openmsupply/remote-server/pull/334) - f986d654feeab9e04187fb07c2e7fc70e9669c89

I am a bit confused by the comment, types in this document just meant to describe the error (we will be coding them in rust). 

> in general the expressive errors are great for debugging but not ideal for coding.

Not suggesting this is how it would be coded, up to front end, this is just a description of errors (and focus is on the consumer, if this is bad form consumer point of view, let me know exactly what the errors should be and will change, see below)

> I would like to see a more consistent type:

> interface ValidationError<T> extends CustomError {
>  code: ErrorCode,
>  field:  keyof T
> }

Is this different from: https://github.com/openmsupply/remote-server/pull/313#discussion_r704791066

> really like the idea of typing errors if that's possible,

Again i am confused, errors are all typed (quite strongly)

I think I am missing something ?

2021-09-21 00:11 UTC, andreievg commented on docs/content/docs/api/custom_errors.md
> +  RecordNotFound = "RECORD_NOT_FOUND",
async graphql doesn't know about DB (as per pattern description of error types)

2021-09-21 00:12 UTC, andreievg commented on docs/content/docs/api/mutations.md
> +}
it's changed now, idk, my bad

2021-09-21 00:13 UTC, andreievg commented on docs/content/docs/api/mutations.md
> +    allInvoiceLines: [UpsertCustomerInvoiceLineInput]
great idea, this was updated in the mutation reshuffle [upstream](https://github.com/openmsupply/remote-server/pull/334) - b4eb01435f9622d3d95be5175e5792d40f50a0ef

2021-09-21 00:14 UTC, andreievg commented on docs/content/docs/api/mutations.md
> +type InsertCustomerInvoiceLineInput = {
Thanks, it's fixed

2021-09-21 00:19 UTC, andreievg commented on docs/content/docs/api/mutations.md
> +As you can see an insert invoice mutation requires all invoice lines to be of [InsertCustomerInvoiceLineInput](/docs/api/mutations/#customer-invoice-line-insert) type, whereas in update invoice mutat
Ohh i think this was an error on my part, that line should have read `[InsertCustomerInvoiceLineInput] or [UpdateCustomerInvoice]`

I update it here [upstream](https://github.com/openmsupply/remote-server/pull/334) - b4eb01435f9622d3d95be5175e5792d40f50a0ef

2021-09-21 00:19 UTC, andreievg commented on docs/content/docs/api/mutations.md
> +Customer invoice lines are always linked to an invoice, and are mutated via [upsertCustomerInvoice](/docs/api/mutations/#customer-invoice).
thanks, yeah. That should be changed now

2021-09-21 00:28 UTC, andreievg commented
@joshxg @mark-prins 

I've updated to use insert and update on invoice mutations (still lines are upserted for update invoice, but insert only for insert invoice). And changed errors slightly to have some hierarchy. I did the changes in upstream branch https://github.com/openmsupply/remote-server/pull/334, as I've reshuffled things there and there would be too many conflicts if i did it in this branch.

One thing I am still confused about is this comment: https://github.com/openmsupply/remote-server/pull/333#discussion_r709841017

Is it suggesting something to be changed in actual error shapes ? Or is it to do with representing error with typescript generics (if it's the later I have some pushback, it should be very easy to read all possible errors, generics help in dev but I dont' think they would add value in docs ?) I did make this change to be a bit stronger typed with RecordNotFound error: cbf601282bec854e9f0d64b818e7bd7c376d90ff

2021-09-22 02:18 UTC, joshxg commented
@andreievg Sorry bit confused. Should we just merge and then comment on the supplier invoice one? Are all the changes there?

2021-09-22 02:18 UTC, joshxg approved these changes

2021-09-22 08:03 UTC, joshxg commented on docs/content/docs/api/mutations.md
> +    numberOfPacks: number
Ah of course, thanks 🤦  

This is the same in mSupply for stocktake lines for newly added batches (except mSupply uses a non-null `item_line_ID` for a non-existent item_line). 

Maybe we need to flag this for a better solution as it's not ideal to have trans lines with no item line imo (I will continue to say item line not stock line for approx. 7 months, sorry!).. maybe we need placeholder item lines instead 🙄

2021-09-22 08:04 UTC, joshxg commented on docs/content/docs/api/custom_errors.md
> +  StockLineIdMissingInInvoiceLine =  "STOCK_LINE_ID_MISSING_IN_INVOICE_LINE"
Aye yeah sorry not very clear. Bundle size was my concern. I know it's premature. Just, if there are ~500 references to ~10byte error codes in the JS, it could be a couple KB we could save on some bundles (also lazy loading some parts etc, so less).

Maybe something we could optimise in a build step in the future..

2021-10-12 03:11 UTC, andreievg commented
Going to address remaining comments, tomorrow, but want to merge for now: (will merge downstream PR https://github.com/openmsupply/remote-server/pull/335)
https://github.com/openmsupply/remote-server/issues/431

2021-10-12 03:11 UTC, closed without merging