283 sync integration and tests
openmsupply/remote-server pull request #339
Opened 2021-09-16 04:41 UTC by clemens-msupply

This PR integrates the sync record import into the sync actor. The integration logic goes through a topologically sorted list of sync records, e.g. `["name", "item", "store"...] `, and integrates matching records one after another, each in one transaction.

Should this further be split up? e.g. if there are many name records should the names be integrated in batches?

Most of the PR is related to the test. I tried to reuse test data and logic from the other tests. I plan to move the test_data module one level up but I thought I first get some feedback if you have other ideas about the test...

2021-09-16 08:11 UTC, andreievg requested changes
Looks great, only one change request, the rest are just comments, stylistic suggestions and questions

And the request is about running the whole insert in a transaction

2021-09-16 08:11 UTC, andreievg commented on src/util/sync/mod.rs
> +            self.integrate_central_records(repositories.as_ref())
just wondering why as_ref ?

2021-09-16 08:11 UTC, andreievg commented on src/util/sync/translation/mod.rs
> +pub fn translation_records() -> Vec<String> {
good use of static list i think

2021-09-16 08:11 UTC, andreievg commented on src/util/sync/mod.rs
> +            import_sync_records(repositories, &records).await?;
Otherwise there is no need for transaction since referential integrity is guaranteed with topological order

2021-09-16 08:36 UTC, andreievg commented
> Should this further be split up? e.g. if there are many name records should the names be integrated in batches?

I forgot to reply, but I think I've answered it in one of the comments, on the contrary I think it should all be in one transaction, but topologically ordered.

2021-09-16 19:53 UTC, clemens-msupply commented on src/util/sync/translation/test_data/item.rs
> +    "8F252B5884B74888AAB73A0D42C09E7F",
You mean full real sync records? yes we can do that as well.

The main thing I wanted to test here is records that have the cursors out of order so that I need to order them correctly. I think that is not really clear from the test data, happy to do some more refactoring if needed...

2021-09-16 20:00 UTC, clemens-msupply commented on src/util/sync/translation/test_data/item.rs
>              name: "Non stock items 2".to_owned(),
Yes I had the same thought. Why I did it is to be able to reuse the data and because its easier see what you have in the file, e.g. before it was difficult to see how many upsert records and how many init records there are. Or for the store data test it is easy to see now that you have three invalid stores that shouldn't be imported...

2021-09-16 20:11 UTC, clemens-msupply commented on src/database/repository/diesel/central_sync_buffer.rs
> +            .order(cursor_id.asc())
ok thanks, think it gets even more tricky if, e.g. a Name is deleted and other items need to be deleted first. Or if an item get created -> deleted -> created (probably not even entirely unlikely).

2021-09-16 20:13 UTC, clemens-msupply commented on src/database/repository/diesel/master_list_line.rs
> +    pub async fn find_one_by_id(
Its only used for testing at the moment...

2021-09-16 20:21 UTC, clemens-msupply commented on src/util/sync/mod.rs
> +                .map(|row| SyncRecord {
Thanks, SyncRecord has the SyncType in it but I guess in the future that will be in the CentralSyncBufferRow as well, right? I can address it in another PR and only use CentralSyncBufferRow.

2021-09-16 20:24 UTC, clemens-msupply commented on src/util/sync/mod.rs
> +            self.integrate_central_records(repositories.as_ref())
In the actor we have Data<RepositoryRegistry> (Data comes from actix) and I only need &RepositoryRegistry. Not 100% sure though that this is the way to get it out there...

2021-09-16 20:45 UTC, clemens-msupply commented on src/util/sync/translation/mod.rs
> +pub fn translation_records() -> Vec<String> {
thanks done in 79c7f0a

Related to that, at the moment the developer has to remember to put the translation into the list when adding a new translation which is a bit error prone. I was wondering if we should use a "Translator" trait instead (think you had something like that in your first prototype) e.g. 

```rust
trait Translator {
  fn record_name() -> String;
  // async for complex translations
  async fn try_translate(...);
}
```
and then just have a list of sorted Translators

2021-09-16 21:03 UTC, clemens-msupply commented on src/util/sync/mod.rs
> +            import_sync_records(repositories, &records).await?;
ok no problem, my concern was the memory consumption for the initial syncs (e.g. on mobile) and by doing it this way I could easily split it up in smaller batches...

If memory is a problem, I can put the translation logic into a TranslationRepository and to read/write batches in one transaction.

(Post M1 discussion, I don't think that logic in a TranslationRepository is a clean solution and we better have a concept of a "Tx/RequestContext/StorgeContext" in our business logic, e.g. to avoid read skew in graphgl queries.)

2021-09-16 23:54 UTC, andreievg commented on src/database/repository/diesel/central_sync_buffer.rs
> +            .order(cursor_id.asc())
thankfully we will be deleting any central data that have dependent relations. and remote data deletes should never come through (as the data is only editable on remote)

2021-09-16 23:55 UTC, andreievg commented on src/util/sync/mod.rs
> +                .map(|row| SyncRecord {
> Thanks, SyncRecord has the SyncType in it but I guess in the future that will be in the CentralSyncBufferRow as well, right?

yep

> I can address it in another PR and only use CentralSyncBufferRow

Sure, i was just making a note

2021-09-17 00:03 UTC, andreievg commented on src/util/sync/mod.rs
> +            import_sync_records(repositories, &records).await?;
> my concern was the memory consumption for the initial syncs
I did some number crunching as this was also my concern, it seemed ok when i did, but i only though about pure data size (not the extensive ORM boilerplate objects).

Keen to discuss this further post M1 but if we don't do the whole thing in transaction there is no reason to have transactions in sync at all (another alternative was to crawl through buffer and find all relations and batch those, but that's very complex)

> we better have a concept of a "Tx/RequestContext/StorgeContext" in our business logic, 

Keen to hear about this

2021-09-17 00:04 UTC, andreievg commented on src/util/sync/mod.rs
> +            self.integrate_central_records(repositories.as_ref())
ok, did &repositories not work ?

2021-09-17 00:09 UTC, andreievg commented on src/util/sync/translation/mod.rs
> +pub fn translation_records() -> Vec<String> {
Yep, this is what i had in mind at the start (different names though): https://github.com/openmsupply/remote-server/pull/272/files

> Related to that, at the moment the developer has to remember to put the translation into the list when adding a new translation which is a bit error prone

Still have to have a list somewhere right ? Hopefully tests would catch errors btw

2021-09-17 00:13 UTC, andreievg approved these changes
Thanks Clemens, approving, although I still think we should do the whole thing in transaction, kind of shows the intent of all of the work we've done with buffering and transaction.

2021-09-17 00:40 UTC, clemens-msupply commented on src/util/sync/mod.rs
> +            self.integrate_central_records(repositories.as_ref())
yes that works, thanks! 94a45c1

2021-09-17 00:41 UTC, clemens-msupply commented on src/util/sync/translation/mod.rs
> +pub fn translation_records() -> Vec<String> {
yes there would be a list of Translator, but yes tests would hopefully catch these basic errors and we don't need it

2021-09-17 00:53 UTC, clemens-msupply commented on src/util/sync/mod.rs
> +            import_sync_records(repositories, &records).await?;
The main idea is that every API request or Sync operation can operate in a single tx. Not sure if it will be an issue but in this way we could, for example, avoid that concurrent API mutations lead to inconsistent data because two requests mutating the same data...

There is also this discussion: https://github.com/openmsupply/remote-server/discussions/300

2021-09-17 00:56 UTC, merged

2021-09-17 00:56 UTC, clemens-msupply commented
Thanks for the review. I agree that it would be nicer to run the whole sync in one transaction. I will merge now and then work on it and use CentralSyncBufferRow instead of SyncRecord.

2021-09-17 01:21 UTC, andreievg commented on src/util/sync/mod.rs
> +            import_sync_records(repositories, &records).await?;
sweet, just for the record, i think transactions are important : ), and i complete missed the discussions in this repo