304 4 add stock line to items
openmsupply/remote-server pull request #342
Opened 2021-09-16 15:58 UTC by andreievg

Sorry for big diff, i should have done renaming first. the [last commit](https://github.com/openmsupply/remote-server/commit/dc3676b633b472b8f6cc6c78feef33f8b1a8b3b5) is the main change (under 200 lines)

### Changes
* Renamed item line to stock line
* Added schema changes with new translations
* Removed old loaded and implemented loaded for StockLineRepository

Didn't know what to test, i did quite a few manual tests with GraphQL, all working fine.

(hindsight, best not too get far ahead with prototype, just show how things can work, otherwise quite a lot of changes needed when requirements are clarified)

2021-09-16 15:59 UTC, andreievg commented on src/server/service/graphql/schema/types/stock_line.rs
> +pub struct StockLineQuery {
i thought of just deriving this on just deriving this on StockLineRow, but it seemed like the wrong place to do it ?

You can see the from clause is just a direct mapping from StockLineRow

2021-09-16 16:01 UTC, andreievg commented on src/database/repository/diesel/mod.rs
> +    repositories.insert(DataLoader::new(StockLineRepository::new(pool.clone())));
I can't see the need for having two seperate holders, one for repository and one for loaders, i think we should just combine them into one (maybe database_context ?)

2021-09-16 16:03 UTC, andreievg commented on src/server/service/graphql/schema/types/item.rs
> +        let repository = ctx.get_repository::<DataLoader<StockLineRepository>>();
as per another comment, i think this should just be `get()` or `database_context`

2021-09-16 22:45 UTC, clemens-msupply commented on src/server/service/graphql/schema/types/stock_line.rs
> +pub struct StockLineQuery {
Would be really cool if you could do something like this:

``` rust
#[derive(...)] 
type StockLineQuery = StockLineRow;
```

2021-09-16 22:51 UTC, clemens-msupply commented on src/database/repository/diesel/mod.rs
> +    repositories.insert(DataLoader::new(StockLineRepository::new(pool.clone())));
Could the loaders also be created on the stack on demand, e.g. `let loader = ItemLoader::new(repositories)`?

2021-09-16 23:39 UTC, clemens-msupply requested changes

2021-09-16 23:39 UTC, clemens-msupply commented on src/database/repository/mod.rs
> +    ActixThredPoolCanceled,
thred -> thread (in comment as well)

Is that a repository error though? Chris had some ideas about errors: https://github.com/openmsupply/remote-server/discussions/301

2021-09-17 01:02 UTC, andreievg commented on src/database/repository/diesel/mod.rs
> +    repositories.insert(DataLoader::new(StockLineRepository::new(pool.clone())));
Hmm, is this for testing repositories?  i am not sure, i think it's async graphql specific. Also it has to be one common loader so that resolvers know that there is an async operation waiting for the operation to be fetched (i.e. when loads of items are requested, each individual resolver for stockline will be called and some magic know for them to wait for main query to finish)

2021-09-17 01:08 UTC, andreievg commented on src/database/repository/mod.rs
> +    ActixThredPoolCanceled,
36a7384fbe942bbe32a3d67ef0bb80b1a31f0621

it has to map to repository error, diesel::result::Error doesn't work in the loader, there is 0 extra information in the Canceled enum of BlockedErrror btw, maybe it's good to also say where it happened (which loader ?), but it would require mapping directly (not using from), can do that if you think it's better.

2021-09-17 01:24 UTC, clemens-msupply commented on src/database/repository/mod.rs
> +    ActixThredPoolCanceled,
The anyhow crate that Chris mentioned might be useful here, they had a feature like that. I don't have the full picture yet though how it would all fit together...

Another thought, maybe simply remove Actix from the error name to make the error more generic?

2021-09-17 01:32 UTC, wlthomson commented on src/database/repository/diesel/mod.rs
> +    repositories.insert(DataLoader::new(StockLineRepository::new(pool.clone())));
The reason they're separate is just to keep it easy to remove the loaders if we decided to go with a different pattern. I agree that they should be combined: repositories probably shouldn't be used directly by graphql if we are using loaders.

2021-09-17 04:54 UTC, andreievg commented on src/database/repository/diesel/mod.rs
> +    repositories.insert(DataLoader::new(StockLineRepository::new(pool.clone())));
> I agree that they should be combined: repositories probably shouldn't be used directly by graphql if we are using loaders.

How do you pass a filter or sort or pagination InputObject to loaders ? (I think it's fine to use repositories in GraphQL)

2021-09-17 04:57 UTC, andreievg commented on src/database/repository/mod.rs
> +    ActixThredPoolCanceled,
cbf4fd258fc5dda004a8dabef56415195dcdacf0

hmm, requires a deeper thought

2021-09-17 06:47 UTC, andreievg commented on src/server/service/graphql/schema/types/stock_line.rs
> +pub struct StockLineQuery {
technically it's possible to make a macro like this (probably declarative function-like macro vs procedural, the former replaces code vs later adds to it). I think we would need to specify the source filename of StockLineRow definition (and use `syn:File` to parse that file and find StockLineRow).

This is all very deep lol, but i had the same question so thought of checking out how it could be done.

The call would be like (this is just out of interest, no way suggesting we should do it)
```rust
duplicate_struct!({
        prefix -> "#[derive(PartialEq, Debug)]"
        to -> StockLineQuery
        from -> StockLineRow
        fromLocation -> "src/database/schema/stock_line.rs",
        deriveFrom -> true
     });
```

2021-09-17 09:35 UTC, wlthomson approved these changes

2021-09-17 09:35 UTC, wlthomson commented on src/database/repository/diesel/mod.rs
> +    repositories.insert(DataLoader::new(StockLineRepository::new(pool.clone())));
That was phrased a bit badly, I mean't to say we shouldn't call repositories directly in the instances where we are using a dataloader (i.e. the data loader should call the repository and batch the results). I agree with using both repositories and data loaders in gql, exposed via a unified registry. Does that clarify?

2021-09-17 09:35 UTC, wlthomson commented on src/server/service/graphql/schema/types/item.rs
> +        let repository = ctx.get_repository::<DataLoader<StockLineRepository>>();
I'd be happy just with `ctx.get`!

2021-09-19 20:11 UTC, clemens-msupply commented on src/server/service/graphql/schema/types/stock_line.rs
> +pub struct StockLineQuery {
haha that would work but I guess you still can't pass a StockLineRow straight into a method that expect a StockLineQuery? or would there be a `from` implementation in the macro? but `from` would still unnecessarily copy the structs at runtime, wouldn't it?

2021-09-19 20:52 UTC, andreievg commented
@clemens-msupply, I think i've address pending change requests

2021-09-19 20:54 UTC, clemens-msupply approved these changes

2021-09-19 20:55 UTC, andreievg commented on src/database/repository/diesel/mod.rs
> +    repositories.insert(DataLoader::new(StockLineRepository::new(pool.clone())));
what do you mean by 'call' ?
Btw we can also make DataLoader instance a field in a repository, i kind of think they are integral part of repository, i guess we can discuss this at the start of m2

2021-09-19 20:57 UTC, merged