Use NaiveDate type for the expiry date
openmsupply/remote-server pull request #383
Opened 2021-09-30 01:03 UTC by clemens-msupply

2021-09-30 06:08 UTC, wlthomson requested changes

2021-09-30 06:08 UTC, wlthomson commented on src/database/mock/invoice_line.rs
> +        expiry_date: Some(Utc::now().naive_utc().date()),
We probably want our test data to be identical across different tests, otherwise our test results may not be replicable. I would suggest just choosing an arbitrary date for this?

2021-09-30 06:08 UTC, wlthomson commented on src/database/repository/tests.rs
> +                expiry_date: Some(NaiveDateTime::from_timestamp(2 * 24 * 60 * 60, 0).date()),
Why the timestamp? Could perhaps simplify with something like `from_ymd`?

2021-09-30 06:08 UTC, wlthomson commented on migrations/sqlite/00000105_create_stock_line_table/up.sql
> +    expiry_date DATE,
Does this work? I thought SQLite didn't have an inbuilt type for dates or times (https://www.sqlite.org/datatype3.html)?

2021-09-30 06:38 UTC, clemens-msupply commented on src/database/repository/tests.rs
> +                expiry_date: Some(NaiveDateTime::from_timestamp(2 * 24 * 60 * 60, 0).date()),
done 731eb54 thanks

2021-09-30 06:38 UTC, clemens-msupply commented on src/database/mock/invoice_line.rs
> +        expiry_date: Some(Utc::now().naive_utc().date()),
done 731eb54 thanks

2021-09-30 06:39 UTC, clemens-msupply commented on migrations/sqlite/00000105_create_stock_line_table/up.sql
> +    expiry_date DATE,
Don't know why it works (diesel or sqlite) but changed it to text ebc1a80

2021-10-01 05:45 UTC, wlthomson approved these changes

2021-10-01 05:45 UTC, wlthomson commented on src/database/mock/invoice_line.rs
> +        expiry_date: Some(NaiveDate::from_ymd(2020, 8, 7)),
If we use these in production we should probably add some unit tests to make sure the dates are being parsed and serialised as we expect them to be... for now seems OK though.

2021-10-03 19:35 UTC, merged