626 add not equal filter and use macros in domain repos
openmsupply/remote-server pull request #627
Opened 2021-11-29 12:14 UTC by andreievg

Closes: #626 

Please see issue for motivation of this PR.

Quite a few changes but they are all very repetitive, main areas of change origin is in domain/

Quite like the macro way of doing filtering and sorting,

2021-11-30 21:09 UTC, clemens-msupply requested changes
Yes agree the diesel macros make sense here.

My theory is that if you need a macro it indicates that something else is broken/too complex and in this case it strongly points to Diesel :)

I think the AddToFilter trait is too much though. I am fine with the builder pattern but I also added a baseline example to show how easy (but verbose) it is to setup a filter with "simple" Rust.

2021-12-01 22:35 UTC, andreievg commented on service/src/invoice/outbound_shipment/delete/validate.rs
> +    id: &String,
It was due to parameter requirements in EqualFilter implementation (it was &String), i think this is way better way of doing it:  https://github.com/openmsupply/remote-server/pull/636

2021-12-01 22:36 UTC, andreievg commented on domain/src/invoice.rs
> +        self.id = self.id.add(f);
As per the comment in the issue, adding a new variation to filter require quite a few changes, wanted to make it streamline

I wanted to be able to add a new filter (i.e. not_equal_to) and be able to use it everywhere with minimal changes. I agree AddToFilter is overkill, there is a refactor here: https://github.com/openmsupply/remote-server/pull/636 which i think is a good way to do it.

Not really sure what you've suggested (it's just for equal_to, but there are three variants)

2021-12-02 02:27 UTC, clemens-msupply approved these changes

2021-12-02 03:54 UTC, merged