657 apply number sequence logic on invoices
openmsupply/remote-server pull request #658
Opened 2021-12-13 14:47 UTC by andreievg

Closes #657 

Sorry a few changes from the original implementation.

* Added type to number row (want to be type strict, and avoid concatenating string to identify database entities). This made id a uuid, in previous repo test "test_counter_name" would only work for one store, as the id wouldn't be unique across stores (although it was tested with store_id)
* Ended up relocating number logic to service, I thought it was too much logic in repo (including transaction logic), I feel like the logic is responsibility of service.
* Added number logic to both inbound and outbound shipments.

Really wanted to make number service accept ServiceContext, and went a fair way down that track (ServiceContext would have transaction method, which is really a one liner), but it required quite a lot of changes to the inbound/outbound insert services (especially when they are used in batch), so refrained, but i think all services should use ServiceContext and it should have transaction method (closure gets ServiceContext ref as param)

Didn't end up doing queries for inbound and outbound (where invoice number is the parameters), thought to keep PR to scope (I think i already went over the scope)

2021-12-13 20:41 UTC, clemens-msupply requested changes
Yes the ServiceContext tx is a bit of a problem. It would be a bit unfortunate to have the tx in the ServiceContext, i.e the ServiceContext would be responsible for the tx and for holding unrelated stuff like loggers.
But on the other hand I am not sure if a more traditional way of having `SomeService::new(con: Rc<StorageConnection>, logger, other_args)` and constructing it in a factory would be much better.

2021-12-13 20:41 UTC, clemens-msupply commented on service/src/number.rs
> -            let row = repo.increment(counter_id, store_id)?;
Oh yes there was a bug there counter_id should have been updated to something like "{coutner_id}_{store_uid}"

2021-12-14 03:51 UTC, andreievg commented on repository/migrations/postgres/00000118_number_table/up.sql
> +);
Do you mean we dont' use enums (pg) or check (sqlite) schema (across the board, including types of invoices etc..) ?. I think it's important to have descriptive schema (don't use strings and constants if enums are used). We shouldn't need to look at code to figure out what are the possible values for these kind of things

2021-12-14 03:54 UTC, andreievg commented on repository/migrations/postgres/00000118_number_table/up.sql
> +    type number_type NOT NULL
Yeah, and i would avoid using concatenated string literals as identifiers of record meaning

2021-12-14 04:10 UTC, andreievg commented
> Yes the ServiceContext tx is a bit of a problem. It would be a bit unfortunate to have the tx in the ServiceContext, i.e the ServiceContext would be responsible for the tx and for holding unrelated stuff like loggers.

I don't see it being a problem, just like a service could be a class with 'state', ServiceContext becomes common states across services used within an operation (they share the state via ServiceContext which is passed via params). This way services becomes really reusable and simple.

> But on the other hand I am not sure if a more traditional way of having SomeService::new(con: Rc<StorageConnection>, logger, other_args) and constructing it in a factory would be much better.

`SomeService::new(con: Rc<StorageConnection>, logger, other_args)`, I think the transaction logic is already pretty complex (with lifetime bounds and Cell within StorageConnection), i think it would becomes even harder more complex if Rc<StorageConnection> is the parameters of transaction closure. Would be good to see an example of this.

Also wouldn't you need to pass along logger and other_args to other services that a services might use ? Wouldn't it be better at that stage to user ServiceContext to share state between services ?

Btw this is what ServiceContext as transaction would look like
```rust
impl ServiceContext {
    pub fn transaction_sync<'a, T, E, F>(&'a self, f: F) -> Result<T, TransactionError<E>>
    where
        F: FnOnce(&'a ServiceContext) -> Result<T, E>,
    {
        self.connection.transaction_sync(|_| f(self))
    }
}

///
pub fn service_1(ctx: ServiceContext) {
    ctx.transaction_sync(|ctx_tx| {
        // do something
        service_2(ctx);
        Ok(())
    });

pub fn service_2(ctx: ServiceContext) {
    ctx.transaction_sync(|ctx_tx| {
        // do something else
        Ok(())
    });
}
```

2021-12-14 22:08 UTC, clemens-msupply commented on repository/migrations/postgres/00000118_number_table/up.sql
> +);
the only advantage I see with enums (when using a type safe language) is that you can't mess update the DB by writing directly to the DB but think editing the DB directly is never a good idea. Otherwise its just dev overhead. But yes you could get more info from the schema (if schema and code is in sync).

In this specific case my idea was to have a general purpose counter which is basically just a HashMap<String, i64> associated with a store. How it is used is up to a higher level. Why restrict it's usage?

2021-12-14 22:48 UTC, clemens-msupply commented
Two nested transaction_sync is bit weird but would work. We could get even more hacky though and just use the parent ServiceContext and ignoring the closure parameter. The only reason I put the tx into the transaction_sync closure parameter was to indicate that its a new transaction but implementation wise its still the same StorageConnection. For example:

```rust
   pub fn service_1(ctx: ServiceContext) {
    ctx.connection.transaction_sync(|_| {
        // do something
        service_2(&ctx);
        Ok(())
    });
```

> Also wouldn't you need to pass along logger and other_args to other services that a services might use ? Wouldn't it be better at that stage to user ServiceContext to share state between services ?

I would let the service provider initialize the services with the correct arguments (haven't looked into details though)...

2021-12-14 23:11 UTC, clemens-msupply commented on repository/migrations/postgres/00000118_number_table/up.sql
> +);
one more argument against enums, you need a DB migration (and test it) every time you need a new counter

2021-12-14 23:26 UTC, andreievg commented
> I would let the service provider initialize the services with the correct arguments (haven't looked into details though)..

So if service is used within a service you would pass through service provider to it (a service provider instance with already the logger etc in it ? )

2021-12-14 23:34 UTC, andreievg commented
> Two nested transaction_sync is bit weird but would work. 
We could get even more hacky though and just use the parent ServiceContext and ignoring the closure parameter. The only reason I put the tx into the transaction_sync closure parameter was to indicate that its a new transaction but implementation wise its still the same StorageConnection. For example:

Hmm, happy with that, as long as you think it's clear that ctx holds the transaction. Like, what was the reason to have StorageConnection passed to transaction closure in StorageConnection.transaction methods ? (I think it was for clarity ?)

Agree that it's wired to reimplement transaction_sync in ServiceContext.

2021-12-14 23:54 UTC, andreievg commented on repository/migrations/postgres/00000118_number_table/up.sql
> +);
> the only advantage I see with enums (when using a type safe language) is that you can't mess update the DB by writing directly to the DB but think editing the DB directly is never a good idea. Otherwise its just dev overhead.

I think the biggest advantage is knowing what values could potentially exist for field, if you take any of mSupply 4D type or status fields, you will have to dig through code to figure out what are the possible values for them. I mean would you know what are all the possible number types in existing mSupply, and how would you find out ?

> But yes you could get more info from the schema (if schema and code is in sync).

I think code and schema are complete coupled, so have to be always in sync ?

> In this specific case my idea was to have a general purpose counter which is basically just a HashMap<String, i64> associated with a store. How it is used is up to a higher level. Why restrict it's usage?

I think it's the same reason that we (and rust) use enums for errors (all errors can just be a string).

> one more argument against enums, you need a DB migration (and test it) every time you need a new counter

It's pretty hard to do migrations like this on sqlite table (well any alter type migrations, i'll be happy with removing the check constraint for those, but for postgres, it's trivial).

You have 'and test it' in brackets, is it more testing then normal test that will be added when new number type is added otherwise ?

```sql
-- postgres
ALTER TYPE colors ADD VALUE 'orange' AFTER 'red';
```

Although I can see an issue with plugins or other things needing counters, but I am really drive by being type safe and type strict (I think it's a huge advantage), I would prefer a string field sub_type if we are going with dynamic number types.

2021-12-15 00:42 UTC, clemens-msupply commented on repository/migrations/postgres/00000118_number_table/up.sql
> +);
> know what are all the possible number types in existing mSupply, and how would you find out ?
do you need to? finding out from the Rust code would be quite easy.

> I think code and schema are complete coupled, so have to be always in sync ?
its a manual process though and not typechecked

yes a sub_type column is probably be useful

2021-12-15 00:43 UTC, clemens-msupply commented on repository/migrations/postgres/00000118_number_table/up.sql
> +    type number_type NOT NULL
don't really see anything wrong about it since its only done in one place, either in a repository or a service.

2021-12-15 00:45 UTC, clemens-msupply commented
> > Two nested transaction_sync is bit weird but would work.
> > We could get even more hacky though and just use the parent ServiceContext and ignoring the closure parameter. The only reason I put the tx into the transaction_sync closure parameter was to indicate that its a new transaction but implementation wise its still the same StorageConnection. For example:
> 
> Hmm, happy with that, as long as you think it's clear that ctx holds the transaction. Like, what was the reason to have StorageConnection passed to transaction closure in StorageConnection.transaction methods ? (I think it was for clarity ?)
> 
> Agree that it's wired to reimplement transaction_sync in ServiceContext.

Yes that was for clarity because its an implementation detail that the tx is just the underlying connection and it might be confusing to use the parent connection/tx

2021-12-15 00:46 UTC, clemens-msupply commented
>

2021-12-15 00:49 UTC, clemens-msupply commented
> > I would let the service provider initialize the services with the correct arguments (haven't looked into details though)..
> 
> So if service is used within a service you would pass through service provider to it (a service provider instance with already the logger etc in it ? )

Either pass through the service provider or pass in the required services when creating it, e.g.

```rust
MyService::new(..., service1: dyn Service1Trait, service2: dyn Service2Trait)
```

2021-12-15 00:49 UTC, clemens-msupply approved these changes

2021-12-15 01:54 UTC, andreievg commented on repository/migrations/postgres/00000118_number_table/up.sql
> +);
> do you need to? finding out from the Rust code would be quite easy.

For us two, yeah easy. My thinking is for wider team (and external pps looking at schema). Like say i want to know how the numbers are incremented in inbound shipment, i can quite easily look at number table and see that one of the types is inbound shipment (we can of course document it in schema comments, but i think it's better to let the actual type do the talking)

> its a manual process though and not typechecked

I think every bit of schema should appear somewhere in test right ? Like we wouldn't' be writing diesel query that is untouched by tests somewhere along the line ? I think if our schema is not in sync with code we have an issue.

2021-12-15 01:59 UTC, andreievg commented on repository/migrations/postgres/00000118_number_table/up.sql
> +);
> yes a sub_type column is probably be useful

I think when we hit a use case where we need generic numbers that are not pre defined we can look at that option

2021-12-15 02:00 UTC, andreievg commented on repository/migrations/postgres/00000118_number_table/up.sql
> +    type number_type NOT NULL
But you need to know about it and read the code to figure it out ? vs just looking at the schema. Also to me intuitively it makes a lot of sense to use concrete types rather then string concatenation (when string concatenation is concatenation of type variants)

2021-12-15 02:10 UTC, andreievg commented
> Either pass through the service provider or pass in the required services when creating it, e.g.

Would that mean service provider would need to instantiate each service that other service relies on and pass it on to another service that it instantiates.? Doesn't it add a bit of indirection, and a bit of extra logic in service provider ? Btw by indirection i mean it's pretty clear now in API what is happening, if we abstract things further it might require a bit of jumping around to figure things out.

I think we have a good balance now of dry vs readability, but yeah if there is simpler, cleaner and quicker for future dev, way to do it, be keen to change

2021-12-15 21:30 UTC, merged